load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_test",
    srcs = glob(["src/**/*.rs"]),
    # `//bsmr/packages/rust/remote_execution:remote_execution` is an alias selecting between
    # the internal and OSS impls; autocargo doesn't follow aliases, so point at
    # the OSS rust_library directly for cargo's sake.
    autocargo = {
        "cargo_toml_config": {
            "extra_buck_dependencies": {
                "dependencies": [
                    "fbcode//bsmr/packages/rust/remote_execution/oss/re_grpc:remote_execution",
                ],
            },
        },
    },
    test_deps = [
        "fbsource//third-party/rust:maplit",
    ],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:sorted_vector_map",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_build_api:bsmr_build_api",
        "//bsmr/app/bsmr_build_signals:bsmr_build_signals",
        "//bsmr/app/bsmr_cli_proto:bsmr_cli_proto",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_downward_api:bsmr_downward_api",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_error_derive:bsmr_error_derive",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_execute:bsmr_execute",
        "//bsmr/app/bsmr_execute_impl:bsmr_execute_impl",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_grpc:bsmr_grpc",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_interpreter:bsmr_interpreter",
        "//bsmr/app/bsmr_interpreter_for_build:bsmr_interpreter_for_build",
        "//bsmr/app/bsmr_node:bsmr_node",
        "//bsmr/app/bsmr_resource_control:bsmr_resource_control",
        "//bsmr/app/bsmr_server_ctx:bsmr_server_ctx",
        "//bsmr/app/bsmr_test_api:bsmr_test_api",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/dice/dice_futures:dice_futures",
        "//bsmr/packages/rust/gazebo/display_container:display_container",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/host_sharing:host_sharing",
        "//bsmr/packages/rust/pagable/pagable:pagable",
        "//bsmr/packages/rust/remote_execution:remote_execution",
        "//bsmr/packages/rust/starlark/starlark:starlark",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:libc",
        ],
        "ovr_config//os:macos": [
            "fbsource//third-party/rust:libc",
        ],
    }),
)
