load("@bsmr_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")

oncall("build_infra")

rust_protobuf_library(
    name = "bsmr_downward_api_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bsmr_downward_api_proto.proto",
    deps = [
        "fbsource//third-party/rust:tracing",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_hash:bsmr_hash",
    ],
)

proto_srcs(
    name = "bsmr_downward_api_proto.proto",
    srcs = ["downward_api.proto"],
    visibility = ["PUBLIC"],
)
