# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@root//tests/prelude:py_assertion.bzl", "py_assertion")

oncall("golang")

prelude = native

prelude.go_binary(
    name = "bin",
    srcs = ["main.go"],
    deps = [
        "root//tests/prelude/go/binary/library:lib",
    ],
)

py_assertion(
    name = "check_output",
    script = """
import subprocess
import sys
assert (
    subprocess.check_output([sys.argv[1]]).decode().strip()
    == "hello world"
)
""",
    script_args = ["$(exe_target :bin)"],
)

py_assertion(
    name = "check_exe_extension",
    script = """
import sys
from pathlib import Path
import platform
if platform.system() == "Windows":
    assert (
        Path(sys.argv[1]).suffix == ".exe"
    )
""",
    script_args = ["$(exe_target :bin)"],
)
