# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_log_common.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_log_common",
    srcs = glob([
        "src/**/*.rs",
    ]),
    deps = [
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:flate2",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:serde",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:tokio-stream",
        "root//app/bsmr_client_ctx:bsmr_client_ctx",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_event_log:bsmr_event_log",
        "root//app/bsmr_event_observer:bsmr_event_observer",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
        "root//packages/rust/gazebo/dupe:dupe",
    ],
)
