load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_build_api_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    proc_macro = True,
    deps = [
        "bsmr_build//third-party/rust:convert_case",
        "bsmr_build//third-party/rust:proc-macro2",
        "bsmr_build//third-party/rust:quote",
        "bsmr_build//third-party/rust:syn",
        "root//packages/rust/gazebo/gazebo:gazebo",
    ],
)
