load("@root//tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("build_infra")

bsmr_e2e_test(
    name = "test_select_types",
    srcs = ["test_select_types.py"],
    data_dir = "test_select_types_data",
)
