load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

# Opt-in allocation-site fragmentation profiler (facebook/mem_frag), enabled
# with `-c bsmr_dev.memfrag=true`. The dump watcher must be started post-fork from
# the daemon, so this crate gets the dep + cfg too.
_memfrag = read_config("bsmr_dev", "memfrag", "") == "true"

rust_library(
    name = "bsmr_daemon",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = ["--cfg=bsmr_memfrag"] if _memfrag else [],
    test_deps = [
        "root//app/bsmr_certs:bsmr_certs",
        "bsmr_build//third-party/rust:fbinit",
    ],
    deps = (
        [
            "root//facebook/mem_frag:mem_frag",
        ]
        if _memfrag
        else []
    )
    + [
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:libc",
        "bsmr_build//third-party/rust:rand",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tokio-stream",
        "bsmr_build//third-party/rust:tracing",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_client_ctx:bsmr_client_ctx",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_resource_control:bsmr_resource_control",
        "root//app/bsmr_server:bsmr_server",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/gazebo/dupe:dupe",
        # @oss-disable[end= ]: "//common/rust/gflags:gflags",
    ]
    + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "bsmr_build//third-party/rust:nix",
            # @oss-disable[end= ]: "//bpfjailer/client:bpfjailer_client_rs",
            # @oss-disable[end= ]: "//bpfjailer/client:bpfjailer_handler_polyglot-rs_bindings",
        ],
        "ovr_config//os:macos": [
            "bsmr_build//third-party/rust:nix",
        ],
    }),
)
