load("@fbcode//bsmr/tests:buck_e2e.bzl", "bsmr_e2e_test")
load("@bsmr_build//rules:python_library.bzl", "python_library")

oncall("tae")

python_library(
    name = "fdb_e2e_types",
    srcs = ["types.py"],
    deps = [
        "//bsmr/tests/e2e_util/api:api",
    ],
)

bsmr_e2e_test(
    name = "test_fdb_project",
    srcs = [
        "test_fdb_bxl_java.py",
    ],
    test_with_compiled_bsmr = False,
    test_with_deployed_bsmr = True,
    deps = [
        ":fdb_e2e_types",
        "//bsmr/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)
