load("@char_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_sketches",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:base64",
        "//buck2/packages/rust/setsketch:setsketch",
    ],
)
