// @generated by Hollywood. Do not edit by hand.

import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { rustAffectedAction } from "../../../../../ci/affected.ts";

void runGitHubAction(rustAffectedAction);
