# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_worker_proto.

load("@bsmr_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")
load("@bsmr_build//rules:targets.bzl", "translate_target")

oncall("build_infra")

rust_protobuf_library(
    name = "bsmr_worker_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bsmr_worker_proto.proto",
)

proto_srcs(
    name = "bsmr_worker_proto.proto",
    srcs = ["worker.proto"],
    visibility = ["PUBLIC"],
    deps = [
        translate_target("root//app/bsmr_data:data_proto"),
    ],
)
