load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_build_signals",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:tokio",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/gazebo/cmp_any:cmp_any",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/gazebo:gazebo",
    ],
)
