load("@char_build//rules:rust.bzl", "rust_binary")

rust_binary(
    name = "rust-project",
    srcs = glob([
        "src/**/*.rs",
        "templates/*",
    ]),
    crate_root = "src/main.rs",
    link_style = "static",
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:dunce",
        "fbsource//third-party/rust:elf",
        "fbsource//third-party/rust:rustc-hash",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:serde_path_to_error",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:tracing-subscriber",
    ],
)
