load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_cmd_log_client",
    srcs = glob([
        "src/**/*.rs",
    ]),
    test_deps = [
        "fbsource//third-party/rust:prost",
        "fbsource//third-party/rust:tempfile",
        "fbsource//third-party/rust:zstd",
        "//bsmr/app/bsmr_fs:bsmr_fs",
    ],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:csv",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:linked-hash-map",
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:similar",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-stream",
        "//bsmr/app/bsmr_cli_proto:bsmr_cli_proto",
        "//bsmr/app/bsmr_client_ctx:bsmr_client_ctx",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_event_log:bsmr_event_log",
        "//bsmr/app/bsmr_event_observer:bsmr_event_observer",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_log_common:bsmr_log_common",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/app/bsmr_wrapper_common:bsmr_wrapper_common",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/gazebo:gazebo",
        "//bsmr/packages/rust/superconsole:superconsole",
    ],
)
