load("@bsmr_build//rules:rust.bzl", "rust_binary")

oncall("build_infra")

rust_binary(
    name = "bsmr_expect",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:prost",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-util",
        "//bsmr/app/bsmr_cli_proto:bsmr_cli_proto",
        "//bsmr/app/bsmr_subscription_proto:bsmr_subscription_proto",
    ],
)
