//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Retires the toolchain package that earlier releases generated under `toolchains/`.

//! Earlier releases wrote a generated `toolchains/BUILD.bsmr`, its `bsmr_go_toolchain.bzl`,
//! and the SDK acquisition under `<root>/toolchains/`, whatever `toolchains//` named. The Go
//! toolchain now joins the `toolchains//` package from the lock, so those files either sit in a
//! directory no cell uses or declare `go` a second time. Only files that carry the generator's
//! exact ownership marker are ever touched.

use std::fs;
use std::path::Path;
use std::path::PathBuf;

use super::GoToolchainError;
use super::acquisition::SDK_DIRECTORY;
use super::acquisition::TOOLS_DIRECTORY;
use super::acquisition::owns_acquisition;

/// The directory earlier releases wrote regardless of the configured `toolchains` cell.
const LEGACY_DIRECTORY: &str = "toolchains";
const LEGACY_MANIFEST: &str = "BUILD.bsmr";
const LEGACY_DEFINITION: &str = "bsmr_go_toolchain.bzl";

/// The exact manifest earlier releases generated; any other content belongs to the user.
pub(crate) const GENERATED_MANIFEST: &str = r#"# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Selects Bessemer's generated Go SDK while preserving the default polyglot tools.
# Generated by `bsmr go toolchain`; DO NOT EDIT.

load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load(":bsmr_go_toolchain.bzl", "bsmr_go_toolchains")

system_demo_toolchains(include_go = False)
bsmr_go_toolchains()
"#;

/// The preamble every generated definition starts with; its body varied with the lock.
pub(crate) const GENERATED_DEFINITION_PREFIX: &str = r#"# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines the exact official Go SDK selected by Bessemer's native frontend.
# Generated by `bsmr go toolchain`; DO NOT EDIT.
"#;

/// The generated manifest's toolchains other than Go, which a declared cell keeps.
const DEMO_TOOLCHAINS: &str = r#"load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")

system_demo_toolchains(include_go = False)
"#;

/// Fails, naming each path, while an earlier release's generated toolchain files remain.
pub(crate) fn reject_leftovers(root: &Path, toolchains: &Path) -> Result<(), GoToolchainError> {
    let leftovers = find_leftovers(root, toolchains)?;
    if leftovers.is_empty() {
        Ok(())
    } else {
        Err(GoToolchainError::Leftover(leftovers))
    }
}

/// Removes an earlier release's generated toolchain files.
///
/// In a declared `toolchains` cell at `<root>/toolchains`, the generated manifest defines the
/// cell's package, so it keeps the toolchains it declared other than Go instead of vanishing.
pub(crate) fn remove_leftovers(root: &Path, toolchains: &Path) -> Result<(), GoToolchainError> {
    let legacy = root.join(LEGACY_DIRECTORY);
    for path in find_leftovers(root, toolchains)? {
        if legacy == toolchains && path == legacy.join(LEGACY_MANIFEST) {
            fs::write(&path, DEMO_TOOLCHAINS)
        } else if path.is_dir() {
            fs::remove_dir_all(&path)
        } else {
            fs::remove_file(&path)
        }
        .map_err(|error| GoToolchainError::Write {
            path: path.clone(),
            message: error.to_string(),
        })?;
    }
    if legacy != toolchains && is_empty_directory(&legacy)? {
        fs::remove_dir(&legacy).map_err(|error| GoToolchainError::Write {
            path: legacy,
            message: error.to_string(),
        })?;
    }
    Ok(())
}

/// Lists the generator-owned files under `<root>/toolchains` that the current layout no longer
/// uses. The acquisitions there stay when `toolchains//` still names that directory.
fn find_leftovers(root: &Path, toolchains: &Path) -> Result<Vec<PathBuf>, GoToolchainError> {
    let legacy = root.join(LEGACY_DIRECTORY);
    let mut leftovers = Vec::new();
    let manifest = legacy.join(LEGACY_MANIFEST);
    if read_if_exists(&manifest)?.is_some_and(|content| content == GENERATED_MANIFEST) {
        leftovers.push(manifest);
    }
    let definition = legacy.join(LEGACY_DEFINITION);
    if read_if_exists(&definition)?
        .is_some_and(|content| content.starts_with(GENERATED_DEFINITION_PREFIX))
    {
        leftovers.push(definition);
    }
    if legacy != toolchains {
        for name in [SDK_DIRECTORY, TOOLS_DIRECTORY] {
            let path = legacy.join(name);
            if path.is_dir() && owns_acquisition(&path) {
                leftovers.push(path);
            }
        }
    }
    Ok(leftovers)
}

/// Reads a file that may be absent.
fn read_if_exists(path: &Path) -> Result<Option<String>, GoToolchainError> {
    match fs::read_to_string(path) {
        Ok(content) => Ok(Some(content)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(GoToolchainError::Read {
            path: path.to_owned(),
            message: error.to_string(),
        }),
    }
}

/// Reports whether `path` is a directory with no entries left.
fn is_empty_directory(path: &Path) -> Result<bool, GoToolchainError> {
    match fs::read_dir(path) {
        Ok(mut entries) => Ok(entries.next().is_none()),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(error) => Err(GoToolchainError::Read {
            path: path.to_owned(),
            message: error.to_string(),
        }),
    }
}
