//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Renders the generated Starlark graph for one locked official Go SDK.

//! Lowers one SDK lock into generated Starlark toolchain definitions.
//!
//! Execution-platform selects choose an archive containing runnable compiler tools;
//! target-platform selects choose `GOOS` and `GOARCH` for the artifact being built.
//! Keeping those dimensions separate enables pure-Go cross compilation without trying
//! to execute a target-platform compiler on the host.

use std::fmt::Write as _;
use std::fs;
use std::io::Write as _;
use std::path::Path;

use super::GoSdkArchive;
use super::GoToolchainError;
use super::GoToolchainLock;
use super::validate_lock;

const GENERATED_DEFINITION_PREFIX: &str = r#"# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines the exact official Go SDK selected by Bessemer's native frontend.
# Generated by `bsmr go toolchain`; DO NOT EDIT.
"#;
const TOOLCHAIN_DEFINITION: &str = "toolchains/bsmr_go_toolchain.bzl";
const TOOLCHAINS_BUCK: &str = "toolchains/BUCK";

pub(crate) const LEGACY_TOOLCHAINS_BUCK: &str = r#"load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")

# All the default toolchains, suitable for a quick demo or early prototyping.
# Most real projects should copy/paste the implementation to configure them.
system_demo_toolchains()"#;

const GENERATED_TOOLCHAINS_BUCK: &str = r#"# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Selects Bessemer's generated Go SDK while preserving the default polyglot tools.
# Generated by `bsmr go toolchain`; DO NOT EDIT.

load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")
load(":bsmr_go_toolchain.bzl", "bsmr_go_toolchains")

system_demo_toolchains(include_go = False)
bsmr_go_toolchains()
"#;

/// Writes or verifies the lock and generated toolchain IR without touching custom definitions.
pub(crate) fn write_configuration(
    root: &Path,
    lock: &GoToolchainLock,
    check: bool,
) -> Result<(), GoToolchainError> {
    validate_lock(lock)?;
    let lock_path = root.join(super::LOCK_FILE);
    let buck_path = root.join(TOOLCHAINS_BUCK);
    let definition_path = root.join(TOOLCHAIN_DEFINITION);
    let mut lock_content = serde_json::to_string_pretty(lock)
        .map_err(|error| GoToolchainError::Lock(error.to_string()))?;
    lock_content.push('\n');
    let definition = render_definition(lock)?;
    validate_owned_buck(&buck_path)?;
    validate_owned_generated(&definition_path, GENERATED_DEFINITION_PREFIX)?;
    validate_owned_lock(&lock_path)?;
    let expected = [
        (&buck_path, GENERATED_TOOLCHAINS_BUCK.as_bytes()),
        (&definition_path, definition.as_bytes()),
        (&lock_path, lock_content.as_bytes()),
    ];
    if check {
        let stale = expected
            .iter()
            .filter_map(|(path, bytes)| match fs::read(path) {
                Ok(existing) if existing == *bytes => None,
                _ => Some((*path).clone()),
            })
            .collect::<Vec<_>>();
        if stale.is_empty() {
            return Ok(());
        }
        return Err(GoToolchainError::Stale(stale));
    }
    let toolchains = root.join("toolchains");
    fs::create_dir_all(&toolchains).map_err(|error| GoToolchainError::Write {
        path: toolchains,
        message: error.to_string(),
    })?;
    for (path, bytes) in expected {
        if !matches!(fs::read(path), Ok(existing) if existing == bytes) {
            atomic_write(path, bytes)?;
        }
    }
    Ok(())
}

/// Renders exact official archives for every supported execution host.
fn render_definition(lock: &GoToolchainLock) -> Result<String, GoToolchainError> {
    let mut output = format!(
        r#"{GENERATED_DEFINITION_PREFIX}
load("@prelude//toolchains/go:go_bootstrap_toolchain.bzl", "go_bootstrap_distr", "go_bootstrap_toolchain")
load("@prelude//toolchains/go:go_toolchain.bzl", "go_distr", "go_toolchain")

def _prebuilt_tool_impl(ctx):
    return [DefaultInfo(default_output = ctx.attrs.binary), RunInfo(args = [ctx.attrs.binary])]

_prebuilt_tool = rule(
    impl = _prebuilt_tool_impl,
    attrs = {{"binary": attrs.source()}},
)

def bsmr_go_toolchains():
"#
    );
    render_archives(&mut output, &lock.archives)?;
    let roots = render_host_select(&lock.archives)?;
    output.push_str("    native.alias(\n        name = \"go_sdk_archive\",\n        actual = ");
    output.push_str(&roots);
    output.push_str(",\n        visibility = [\"PUBLIC\"],\n    )\n\n");
    output.push_str(
        "    _prebuilt_tool(\n        name = \"go_bootstrap_wrapper\",\n        binary = \".bsmr-go-tools/go_wrapper\",\n    )\n\n",
    );
    output.push_str(
        "    go_bootstrap_distr(\n        name = \"go_bootstrap_distr\",\n        go_os_arch = ",
    );
    output.push_str(host_tuple_select());
    output.push_str(",\n        go_root = \".bsmr-go-sdk\",\n    )\n\n");
    output.push_str(
        "    go_bootstrap_toolchain(\n        name = \"go_bootstrap\",\n        env_go_arch = ",
    );
    output.push_str(target_arch_select());
    output.push_str(",\n        env_go_os = ");
    output.push_str(target_os_select());
    output.push_str(",\n        go_bootstrap_distr = \":go_bootstrap_distr\",\n        go_wrapper = \":go_bootstrap_wrapper\",\n        visibility = [\"PUBLIC\"],\n    )\n\n");
    output.push_str("    go_distr(\n        name = \"go_distr\",\n        go_os_arch = ");
    output.push_str(host_tuple_select());
    writeln!(
        output,
        ",\n        go_root = \".bsmr-go-sdk\",\n        version = \"{}\",\n    )\n",
        lock.version
    )
    .map_err(|error| GoToolchainError::Render(error.to_string()))?;
    output.push_str("    go_toolchain(\n        name = \"go\",\n        env_go_arch = ");
    output.push_str(target_arch_select());
    output.push_str(",\n        env_go_os = ");
    output.push_str(target_os_select());
    output.push_str(
        ",\n        env_go_experiment = [\"none\"],\n        go_distr = \":go_distr\",\n        visibility = [\"PUBLIC\"],\n    )\n",
    );
    Ok(output)
}

/// Renders immutable official archive declarations in deterministic host order.
fn render_archives(output: &mut String, archives: &[GoSdkArchive]) -> Result<(), GoToolchainError> {
    for archive in archives {
        writeln!(
            output,
            "    native.http_archive(\n        name = \"{}\",\n        sha256 = \"{}\",\n        size_bytes = {},\n        strip_prefix = \"go\",\n        urls = [\"https://go.dev/dl/{}\"],\n    )\n",
            archive_name(archive),
            archive.sha256,
            archive.size,
            archive.filename,
        )
        .map_err(|error| GoToolchainError::Render(error.to_string()))?;
    }
    Ok(())
}

/// Renders the execution-host archive selection shared by the SDK providers.
fn render_host_select(archives: &[GoSdkArchive]) -> Result<String, GoToolchainError> {
    let archive = |os: &'static str, arch: &'static str| {
        archives
            .iter()
            .find(|archive| archive.os == os && archive.arch == arch)
            .map(archive_name)
            .ok_or_else(|| GoToolchainError::MissingArchive {
                version: "locked".to_owned(),
                os,
                arch,
            })
    };
    Ok(format!(
        "select({{\n            \"config//os:linux\": select({{\n                \"config//cpu:arm64\": \":{}\",\n                \"config//cpu:x86_64\": \":{}\",\n            }}),\n            \"config//os:macos\": select({{\n                \"config//cpu:arm64\": \":{}\",\n                \"config//cpu:x86_64\": \":{}\",\n            }}),\n        }})",
        archive("linux", "arm64")?,
        archive("linux", "amd64")?,
        archive("darwin", "arm64")?,
        archive("darwin", "amd64")?,
    ))
}

/// Returns the distribution's execution-platform tuple selection.
fn host_tuple_select() -> &'static str {
    "select({\n            \"config//os:linux\": select({\n                \"config//cpu:arm64\": (\"linux\", \"arm64\"),\n                \"config//cpu:x86_64\": (\"linux\", \"amd64\"),\n            }),\n            \"config//os:macos\": select({\n                \"config//cpu:arm64\": (\"darwin\", \"arm64\"),\n                \"config//cpu:x86_64\": (\"darwin\", \"amd64\"),\n            }),\n        })"
}

/// Returns target architecture selection for pure-Go cross compilation.
fn target_arch_select() -> &'static str {
    "select({\n            \"config//cpu:arm64\": \"arm64\",\n            \"config//cpu:x86_64\": \"amd64\",\n        })"
}

/// Returns target operating-system selection for pure-Go cross compilation.
fn target_os_select() -> &'static str {
    "select({\n            \"config//os:linux\": \"linux\",\n            \"config//os:macos\": \"darwin\",\n        })"
}

/// Produces a stable target name from one archive's platform.
fn archive_name(archive: &GoSdkArchive) -> String {
    format!("go_sdk_{}_{}", archive.os, archive.arch)
}

/// Allows only the legacy init file or a Bessemer-owned toolchain root.
fn validate_owned_buck(path: &Path) -> Result<(), GoToolchainError> {
    match fs::read_to_string(path) {
        Ok(content)
            if content == LEGACY_TOOLCHAINS_BUCK || content == GENERATED_TOOLCHAINS_BUCK =>
        {
            Ok(())
        }
        Ok(_) => Err(GoToolchainError::UserOwned(path.to_owned())),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(GoToolchainError::Read {
            path: path.to_owned(),
            message: error.to_string(),
        }),
    }
}

/// Allows only a missing file or one carrying the exact generated preamble.
fn validate_owned_generated(path: &Path, prefix: &str) -> Result<(), GoToolchainError> {
    match fs::read_to_string(path) {
        Ok(content) if content.starts_with(prefix) => Ok(()),
        Ok(_) => Err(GoToolchainError::UserOwned(path.to_owned())),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(GoToolchainError::Read {
            path: path.to_owned(),
            message: error.to_string(),
        }),
    }
}

/// Allows only a missing or parseable Bessemer-owned lock.
fn validate_owned_lock(path: &Path) -> Result<(), GoToolchainError> {
    match fs::read(path) {
        Ok(bytes) => {
            let lock = serde_json::from_slice::<serde_json::Value>(&bytes)
                .map_err(|_| GoToolchainError::UserOwned(path.to_owned()))?;
            if lock.get("generated_by").and_then(serde_json::Value::as_str)
                == Some(super::GENERATED_BY)
            {
                Ok(())
            } else {
                Err(GoToolchainError::UserOwned(path.to_owned()))
            }
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(GoToolchainError::Read {
            path: path.to_owned(),
            message: error.to_string(),
        }),
    }
}

/// Atomically persists one generated file beside its final destination.
fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), GoToolchainError> {
    let parent = path.parent().ok_or_else(|| GoToolchainError::Write {
        path: path.to_owned(),
        message: "path has no parent".to_owned(),
    })?;
    let mut temporary =
        tempfile::NamedTempFile::new_in(parent).map_err(|error| GoToolchainError::Write {
            path: path.to_owned(),
            message: error.to_string(),
        })?;
    temporary
        .write_all(bytes)
        .map_err(|error| GoToolchainError::Write {
            path: path.to_owned(),
            message: error.to_string(),
        })?;
    temporary
        .persist(path)
        .map_err(|error| GoToolchainError::Write {
            path: path.to_owned(),
            message: error.error.to_string(),
        })?;
    Ok(())
}
