# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

oncall("build_infra")

rust_binary(
    name = "hello_world",
    srcs = ["hello_world.rs"],
    crate_root = "hello_world.rs",
)
