//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Bundles Bessemer's generated Node runtime artifacts.

import { defineConfig, type RolldownOptions } from "rolldown";

import { renderPreamble } from "./ci/license-preamble.ts";

type Artifact = Readonly<{
	input: string;
	output: string;
	target: `node${number}`;
	define?: Readonly<Record<string, string>>;
}>;

const artifacts: readonly Artifact[] = [
	{
		input: "./.github/actions/ci/release-sync/src/index.ts",
		output: ".github/actions/ci/release-sync/dist/index.js",
		target: "node24",
		define: { "import.meta.vitest": "undefined" },
	},
	{
		input: "./.github/actions/ci/cli-reference/src/index.ts",
		output: ".github/actions/ci/cli-reference/dist/index.js",
		target: "node24",
		define: { "import.meta.vitest": "undefined" },
	},
	{
		input: "./.github/actions/ci/verify-sha256/src/index.ts",
		output: ".github/actions/ci/verify-sha256/dist/index.js",
		target: "node24",
		define: { "import.meta.vitest": "undefined" },
	},
	{
		input: "./.github/actions/ci/osv-audit/src/index.ts",
		output: ".github/actions/ci/osv-audit/dist/index.js",
		target: "node24",
		define: { "import.meta.vitest": "undefined" },
	},
	{
		input: "./.github/actions/ci/rust-affected/src/index.ts",
		output: ".github/actions/ci/rust-affected/dist/index.js",
		target: "node24",
		define: { "import.meta.vitest": "undefined" },
	},
	{
		input: "./prelude/toolchains/pnpm/runner.ts",
		output: "prelude/toolchains/pnpm/runner.mjs",
		target: "node18",
	},
	{
		input: "./prelude/typescript/runner.ts",
		output: "prelude/typescript/runner.mjs",
		target: "node18",
	},
];

/** Create one deterministic, self-contained Node artifact configuration. */
function nodeArtifact(artifact: Artifact): RolldownOptions {
	return {
		input: artifact.input,
		platform: "node",
		transform: {
			...(artifact.define === undefined ? {} : { define: { ...artifact.define } }),
			target: artifact.target,
		},
		output: {
			file: artifact.output,
			format: "esm",
			minify: true,
			postBanner: [
				renderPreamble(artifact.output, "dedalus").trimEnd(),
				`// @generated by Rolldown from ${artifact.input}. Do not edit by hand.`,
			].join("\n"),
		},
	};
}

export default defineConfig(artifacts.map(nodeArtifact));
