# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("//:test_utils.bzl", "assert_output", "haskell_binary", "haskell_library")

oncall("build_infra")

_SUPPORTED = host_info().os.is_macos or host_info().os.is_linux

# buildifier: disable=no-effect
haskell_library(
    name = "library",
    srcs = ["Library.hs"],
) if _SUPPORTED else None

# buildifier: disable=no-effect
haskell_binary(
    name = "main",
    srcs = ["Main.hs"],
    deps = [
        ":library",
    ],
) if _SUPPORTED else None

# buildifier: disable=no-effect
assert_output(
    name = "hello-world-check",
    command = "$(exe_target :main)",
    output = "Hello World!",
) if _SUPPORTED else None
