load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_grpc",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:hyper",
        "fbsource//third-party/rust:hyper-util",
        "fbsource//third-party/rust:pin-project",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tonic",
        "fbsource//third-party/rust:tower",
        "//bsmr/app/bsmr_error:bsmr_error",
    ],
)
