# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_grpc.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_grpc",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:hyper",
        "bsmr_build//third-party/rust:hyper-util",
        "bsmr_build//third-party/rust:pin-project",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tonic",
        "bsmr_build//third-party/rust:tower",
        "root//app/bsmr_error:bsmr_error",
    ],
)
