# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@prelude//python:python_wheel.bzl", "python_wheel")
load("//:test_utils.bzl", "assert_output")

oncall("build_infra")

python_wheel(
    name = "wheel",
    libraries = ["//python/library:printlib"],
    python = "py310",
)

python_binary(
    name = "wheel_checker",
    main = "wheel_checker.py",
    resources = {
        "printlib.whl": ":wheel",
    },
)

assert_output(
    name = "check_wheel",
    command = "$(exe_target :wheel_checker)",
    output = "Wheel OK",
)
