load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_event_observer",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "bsmr_build//third-party/rust:assert_matches",
    ],
    deps = [
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:derivative",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:linked-hash-map",
        "bsmr_build//third-party/rust:prost-types",
        "bsmr_build//third-party/rust:regex",
        "bsmr_build//third-party/rust:shlex",
        "bsmr_build//third-party/rust:termwiz",
        "bsmr_build//third-party/rust:tracing",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_test_api:bsmr_test_api",
        "root//app/bsmr_util:bsmr_util",
        "root//app/bsmr_wrapper_common:bsmr_wrapper_common",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/starlark/starlark_map:starlark_map",
        "root//packages/rust/superconsole:superconsole",
    ],
)
