# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for tools/testing/completion/rpm-download.

load("@bsmr_build//rules:export_files.bzl", "export_file")

oncall("build_infra")

export_file(
    name = "download.sh",
)
