# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_interpreter_for_build_tests.

load("@bsmr_build//rules:rust.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "bsmr_interpreter_for_build_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "bsmr_build//third-party/rust:ctor",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:indoc",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:tokio",
        "root//app/bsmr_build_api:bsmr_build_api",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_interpreter:bsmr_interpreter",
        "root//app/bsmr_interpreter_for_build:bsmr_interpreter_for_build",
        "root//app/bsmr_node:bsmr_node",
        "root//app/bsmr_transition:bsmr_transition",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/starlark/starlark:starlark",
    ],
)
