load("@bsmr_build//rules:rust.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "bsmr_interpreter_for_build_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "fbsource//third-party/rust:ctor",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tokio",
        "//bsmr/app/bsmr_build_api:bsmr_build_api",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_interpreter:bsmr_interpreter",
        "//bsmr/app/bsmr_interpreter_for_build:bsmr_interpreter_for_build",
        "//bsmr/app/bsmr_node:bsmr_node",
        "//bsmr/app/bsmr_transition:bsmr_transition",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/gazebo:gazebo",
        "//bsmr/packages/rust/starlark/starlark:starlark",
    ],
)
