load("@bsmr_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")
load("@bsmr_build//rules:targets.bzl", "translate_target")

oncall("build_infra")

rust_protobuf_library(
    name = "bsmr_health_check_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bsmr_health_check_proto.proto",
    deps = [
        "bsmr_build//third-party/rust:prost-types",
        "root//app/bsmr_data:bsmr_data",
    ],
)

proto_srcs(
    name = "bsmr_health_check_proto.proto",
    srcs = ["health_check.proto"],
    visibility = ["PUBLIC"],
    deps = [
        translate_target("root//app/bsmr_data:data_proto"),
    ],
)
