load("@root//tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("build_infra")

bsmr_e2e_test(
    name = "test_what_ran",
    srcs = ["test_what_ran.py"],
    use_compiled_bsmr_client_and_tpx = True,
)

bsmr_e2e_test(
    name = "test_what_failed",
    srcs = ["test_what_failed.py"],
)

bsmr_e2e_test(
    name = "test_log_format",
    srcs = ["test_log_format.py"],
    use_compiled_bsmr_client_and_tpx = True,
)
