load("@fbcode//bsmr/tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("build_infra")

bsmr_e2e_test(
    name = "test_starlark",
    srcs = ["test_starlark.py"],
)

bsmr_e2e_test(
    name = "test_rust_project",
    srcs = ["test_rust_project.py"],
    env = {
        "RUST_PROJECT_BIN": "$(location fbcode//bsmr/tools/rust-project:rust-project)",
    },
)

bsmr_e2e_test(
    name = "test_linker_argsfile",
    srcs = ["test_linker_argsfile.py"],
)

bsmr_e2e_test(
    name = "test_lsp_fbsource",
    srcs = ["test_lsp_fbsource.py"],
)

bsmr_e2e_test(
    name = "test_cpp_gen_cdb",
    srcs = ["test_cpp_gen_cdb.py"],
)

bsmr_e2e_test(
    name = "test_tools",
    srcs = ["test_tools.py"],
    test_with_deployed_bsmr = True,
    use_compiled_bsmr_client_and_tpx = True,
)

bsmr_e2e_test(
    name = "test_install_modifiers",
    srcs = ["test_install_modifiers.py"],
    deps = [
        "fbcode//bsmr/tests/e2e_util:utils",
    ],
)
