load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_profile",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [],
    deps = [
        "fbsource//third-party/rust:inferno",
        "//bsmr/app/bsmr_cli_proto:bsmr_cli_proto",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_interpreter:bsmr_interpreter",
        "//bsmr/packages/rust/starlark/starlark:starlark",
    ],
)
