# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("apple_build_infra")

source_listing()

python_bootstrap_binary(
    name = "build_index_store",
    main = "main.py",
    visibility = [
        "upstream//glean/glass/test/regression:swift-binary",
        "upstream//glean/glass/test/regression:swift-objc-xlang-binary",
        "upstream//glean/lang/swift/tests:tests",
        "upstream//glean/lang/swift/tests:tests-rust-indexer",
    ],
    deps = [
        "prelude//apple/tools/index:merge_index_store_lib",
    ],
)
