load("@root//tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("tcc")

bsmr_e2e_test(
    name = "tests",
    srcs = glob(
        [
            "**/*.py",
        ],
    ),
    compatible_with = ["ovr_config//os:linux"],
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_bsmr = True,
    use_compiled_bsmr_client_and_tpx = True,
)
