load("@char_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")
load("@char_build//rules:targets.bzl", "translate_target")

oncall("build_infra")

rust_protobuf_library(
    name = "buck2_worker_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_worker_proto.proto",
)

proto_srcs(
    name = "buck2_worker_proto.proto",
    srcs = ["worker.proto"],
    visibility = ["PUBLIC"],
    deps = [
        translate_target("//buck2/app/buck2_data:data_proto"),
    ],
)
