load("@bsmr_build//rules:python_library.bzl", "python_library")

oncall("build_infra")

python_library(
    name = "io",
    srcs = glob(["io/*.py"]),
    deps = [
        "//bsmr/tests/e2e_util:utils",
        "//bsmr/tests/e2e_util/api:api",
    ],
)
