load("@fbcode//bsmr/tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("testing_frameworks")

bsmr_e2e_test(
    name = "test_test_inplace",
    srcs = ["test_test_inplace.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    test_with_deployed_bsmr = True,
    use_compiled_bsmr_client_and_tpx = True,
    deps = ["//bsmr/tests/e2e_util:utils"],
)

bsmr_e2e_test(
    name = "test_test_artifacts",
    srcs = ["test_test_artifacts.py"],
    compatible_with = ["ovr_config//os:linux"],
    env = {
        "TESTX_BIN": "$(exe_target fbcode//tae/testx:testx)",
    },
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_bsmr = True,
    use_compiled_bsmr_client_and_tpx = True,
    deps = [
        "//bsmr/tests/e2e_util:utils",
        "//remote_execution/client_lib/wrappers/python:py_re_client_lib",
        "//remote_execution/lib/if:common-py3-types",
        "//remote_execution/lib/if:common-python-types",
        "//remote_execution/lib/if/client_lib:re-client-lib-if-py3-types",
        "//tae/testx:py",
    ],
)

bsmr_e2e_test(
    name = "test_test_details_artifacts",
    srcs = ["test_test_details_artifacts.py"],
    compatible_with = ["ovr_config//os:linux"],
    env = {
        "TESTX_BIN": "$(exe_target fbcode//tae/testx:testx)",
    },
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_bsmr = False,
    use_compiled_bsmr_client_and_tpx = True,
    deps = [
        "//bsmr/tests/e2e_util:utils",
        "//tae/testx:py",
    ],
)

bsmr_e2e_test(
    name = "test_testname_formatting",
    srcs = ["test_testname_formatting.py"],
    compatible_with = ["ovr_config//os:linux"],
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_bsmr = True,
    use_compiled_bsmr_client_and_tpx = True,
    deps = [
        "//remote_execution/client_lib/wrappers/python:py_re_client_lib",  # @autodeps2-fixme-manual
    ],
)

bsmr_e2e_test(
    name = "test_test_remote_execution",
    srcs = ["test_test_remote_execution.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    test_with_deployed_bsmr = False,
    use_compiled_bsmr_client_and_tpx = True,
)

bsmr_e2e_test(
    name = "test_configs",
    srcs = ["test_configs.py"],
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_bsmr = False,
    use_compiled_bsmr_client_and_tpx = True,
    deps = [
        "//bsmr/tests/e2e_util:utilities",
        "//bsmr/tests/e2e_util/api:api",
    ],
)

bsmr_e2e_test(
    name = "test_brr_suite_level_retry",
    srcs = ["test_brr_suite_level_retry.py"],
    skip_for_os = [
        "darwin",
        "windows",
    ],
    test_with_deployed_bsmr = False,
    use_compiled_bsmr_client_and_tpx = True,
)
