# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

oncall("build_infra")

cxx_binary(
    name = "main",
    srcs = ["main.cpp"],
    link_style = "static",
    deps = [":print"],
)

cxx_library(
    name = "print",
    srcs = ["library.cpp"],
    exported_headers = glob(["**/*.hpp"]),
    visibility = ["PUBLIC"],
)
