# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_client_ctx.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_client_ctx",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {
        "cargo_toml_config": {
            "dependencies_override": {
                "dependencies": {
                    "fbinit": {
                        "path": None,
                        "version": "0.2",
                    },
                },
            },
            "extra_buck_dependencies": {
                "dependencies": [
                    (None, "//common/rust/shed/detect_eden:detect_eden"),
                ],
            },
        },
    },
    test_deps = [
        "bsmr_build//third-party/rust:assert_matches",
        "bsmr_build//third-party/rust:indoc",
        "bsmr_build//third-party/rust:lsp-server",
        "bsmr_build//third-party/rust:pretty_assertions",
        "bsmr_build//third-party/rust:tempfile",
    ],
    deps = [
        "bsmr_build//third-party/rust:anyhow",
        "bsmr_build//third-party/rust:async-compression",
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:blake3",
        "bsmr_build//third-party/rust:bytes",
        "bsmr_build//third-party/rust:chrono",
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:console",
        "bsmr_build//third-party/rust:crossterm",
        "bsmr_build//third-party/rust:csv",
        "bsmr_build//third-party/rust:derivative",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:fs4",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:hex",
        "bsmr_build//third-party/rust:httparse",
        "bsmr_build//third-party/rust:humantime",
        "bsmr_build//third-party/rust:itertools",
        "bsmr_build//third-party/rust:libc",
        "bsmr_build//third-party/rust:memmap2",
        "bsmr_build//third-party/rust:object",
        "bsmr_build//third-party/rust:prost",
        "bsmr_build//third-party/rust:prost-types",
        "bsmr_build//third-party/rust:rand",
        "bsmr_build//third-party/rust:regex",
        "bsmr_build//third-party/rust:serde",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:shlex",
        "bsmr_build//third-party/rust:strum",
        "bsmr_build//third-party/rust:sysinfo",
        "bsmr_build//third-party/rust:take_mut",
        "bsmr_build//third-party/rust:termwiz",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tokio-stream",
        "bsmr_build//third-party/rust:tokio-util",
        "bsmr_build//third-party/rust:tonic",
        "bsmr_build//third-party/rust:tracing",
        "root//app/bsmr_build_info:bsmr_build_info",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_event_log:bsmr_event_log",
        "root//app/bsmr_event_observer:bsmr_event_observer",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_health_check:bsmr_health_check",
        "root//app/bsmr_resource_control:bsmr_resource_control",
        "root//app/bsmr_util:bsmr_util",
        "root//app/bsmr_wrapper_common:bsmr_wrapper_common",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/superconsole:superconsole",
        # @oss-disable[end= ]: "//common/rust/shed/detect_eden:detect_eden",
        "bsmr_build//third-party/rust:fbinit",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "bsmr_build//third-party/rust:termios",
            # @oss-disable[end= ]: "//common/rust/identity:identity_env",
        ],
        "ovr_config//os:macos": [
            "bsmr_build//third-party/rust:termios",
        ],
        "ovr_config//os:windows": [
            "bsmr_build//third-party/rust:windows-sys",
        ],
    }),
)
