# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@prelude//http_archive:exec_deps.bzl", "http_archive_exec_deps")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

http_archive_exec_deps(
    name = "exec_deps",
    visibility = ["PUBLIC"],
)
