load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_interpreter",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    test_deps = [
        "fbsource//third-party/rust:tempfile",
        "//bsmr/app/bsmr_hash:bsmr_hash",
    ],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:either",
        "fbsource//third-party/rust:fancy-regex",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:plist",
        "fbsource//third-party/rust:ref-cast",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:triomphe",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/dice/dice_futures:dice_futures",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/gazebo:gazebo",
        "//bsmr/packages/rust/gazebo/strong_hash:strong_hash",
        "//bsmr/packages/rust/pagable/pagable:pagable",
        "//bsmr/packages/rust/starlark/starlark:starlark",
        "//bsmr/packages/rust/starlark/starlark_map:starlark_map",
    ],
)
