load("@bsmr_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")

oncall("build_infra")

rust_protobuf_library(
    name = "buck2_install_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_install_proto.proto",
)

proto_srcs(
    name = "buck2_install_proto.proto",
    srcs = ["install.proto"],
    visibility = ["PUBLIC"],
)
