load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_validation",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:either",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_artifact:bsmr_artifact",
        "//bsmr/app/bsmr_build_api:bsmr_build_api",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_execute:bsmr_execute",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/dice/dice_error:dice_error",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/pagable/pagable:pagable",
    ],
)
