// @generated by Hollywood. Do not edit by hand.
//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Implements the post-merge receipt action.


import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { postMergeReceiptsAction } from "../../../../../ci/post-merge.ts";

void runGitHubAction(postMergeReceiptsAction);
