load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_action_impl",
    srcs = glob(["src/**/*.rs"]),
    # `root//packages/rust/remote_execution:remote_execution` is an alias selecting between
    # the internal and OSS impls; autocargo doesn't follow aliases, so point at
    # the OSS rust_library directly for cargo's sake.
    autocargo = {
        "cargo_toml_config": {
            "extra_buck_dependencies": {
                "dependencies": [
                    "root//packages/rust/remote_execution/oss/re_grpc:remote_execution",
                ],
            },
        },
    },
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:chrono",
        "bsmr_build//third-party/rust:ctor",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:either",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:hex",
        "bsmr_build//third-party/rust:http",
        "bsmr_build//third-party/rust:itertools",
        "bsmr_build//third-party/rust:parking_lot",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:sha1",
        "bsmr_build//third-party/rust:smallvec",
        "bsmr_build//third-party/rust:sorted_vector_map",
        "bsmr_build//third-party/rust:static_assertions",
        "bsmr_build//third-party/rust:tracing",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_action_metadata_proto:bsmr_action_metadata_proto",
        "root//app/bsmr_analysis:bsmr_analysis",
        "root//app/bsmr_artifact:bsmr_artifact",
        "root//app/bsmr_build_api:bsmr_build_api",
        "root//app/bsmr_build_signals:bsmr_build_signals",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_directory:bsmr_directory",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_execute:bsmr_execute",
        "root//app/bsmr_file_watcher:bsmr_file_watcher",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_http:bsmr_http",
        "root//app/bsmr_interpreter:bsmr_interpreter",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/dice/dice_futures:dice_futures",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/host_sharing:host_sharing",
        "root//packages/rust/pagable/pagable:pagable",
        "root//packages/rust/remote_execution:remote_execution",
        "root//packages/rust/starlark/starlark:starlark",
        "root//packages/rust/starlark/starlark_map:starlark_map",
    ],
)
