# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("//cpp:rules.bzl", "cpp_binary")

oncall("build_infra")

cpp_binary(
    name = "main",
    srcs = glob(["*.cpp"]),
    headers = glob(["*.hpp"]),
    toolchain = "toolchains//:cpp",
    deps = [],
)
