# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_transition.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_transition",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:either",
        "bsmr_build//third-party/rust:itertools",
        "bsmr_build//third-party/rust:ref-cast",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_build_api:bsmr_build_api",
        "root//app/bsmr_build_api_derive:bsmr_build_api_derive",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_interpreter:bsmr_interpreter",
        "root//app/bsmr_node:bsmr_node",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/dice/dice_futures:dice_futures",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/pagable/pagable:pagable",
        "root//packages/rust/starlark/starlark:starlark",
        "root//packages/rust/starlark/starlark_map:starlark_map",
    ],
)
