# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_node_tests.

load("@bsmr_build//rules:rust.bzl", "rust_unittest")

oncall("build_infra")

rust_unittest(
    name = "bsmr_node_tests",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    deps = [
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_node:bsmr_node",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/gazebo/dupe:dupe",
    ],
)
