# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@bsmr_build//rules:rust.bzl", "rust_library")
load("@bsmr_build//rules:rust_linkable_symbol.bzl", "rust_linkable_symbol")

oncall("build_infra")

rust_library(
    name = "bsmr_cmd_completion_client",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["bsmr_build//third-party/rust:paste"],
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:clap_complete",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:tokio",
        ":completion_wrapper_bash",
        ":completion_wrapper_fish",
        ":completion_wrapper_zsh",
        ":options_wrapper_bash",
        ":options_wrapper_fish",
        ":options_wrapper_zsh",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_client_ctx:bsmr_client_ctx",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
    ],
)

rust_linkable_symbol(
    name = "completion_wrapper_bash",
    content_str = "src/completion/completion-wrapper.bash",
)

rust_linkable_symbol(
    name = "completion_wrapper_fish",
    content_str = "src/completion/completion-wrapper.fish",
)

rust_linkable_symbol(
    name = "completion_wrapper_zsh",
    content_str = "src/completion/completion-wrapper.zsh",
)

rust_linkable_symbol(
    name = "options_wrapper_bash",
    content_str = "src/completion/options-wrapper.bash",
)

rust_linkable_symbol(
    name = "options_wrapper_fish",
    content_str = "src/completion/options-wrapper.fish",
)

rust_linkable_symbol(
    name = "options_wrapper_zsh",
    content_str = "src/completion/options-wrapper.zsh",
)
