load("@bsmr_build//rules:rust.bzl", "rust_library")
load("@bsmr_build//rules:rust_linkable_symbol.bzl", "rust_linkable_symbol")

oncall("build_infra")

rust_library(
    name = "bsmr_cmd_completion_client",
    srcs = glob(["src/**/*.rs"]),
    test_deps = ["fbsource//third-party/rust:paste"],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:clap_complete",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:tokio",
        ":completion_wrapper_bash",
        ":completion_wrapper_fish",
        ":completion_wrapper_zsh",
        ":options_wrapper_bash",
        ":options_wrapper_fish",
        ":options_wrapper_zsh",
        "//bsmr/app/bsmr_cli_proto:bsmr_cli_proto",
        "//bsmr/app/bsmr_client_ctx:bsmr_client_ctx",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_hash:bsmr_hash",
    ],
)

rust_linkable_symbol(
    name = "completion_wrapper_bash",
    content_str = "src/completion/completion-wrapper.bash",
)

rust_linkable_symbol(
    name = "completion_wrapper_fish",
    content_str = "src/completion/completion-wrapper.fish",
)

rust_linkable_symbol(
    name = "completion_wrapper_zsh",
    content_str = "src/completion/completion-wrapper.zsh",
)

rust_linkable_symbol(
    name = "options_wrapper_bash",
    content_str = "src/completion/options-wrapper.bash",
)

rust_linkable_symbol(
    name = "options_wrapper_fish",
    content_str = "src/completion/options-wrapper.fish",
)

rust_linkable_symbol(
    name = "options_wrapper_zsh",
    content_str = "src/completion/options-wrapper.zsh",
)
