load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_query",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:enum-iterator",
        "bsmr_build//third-party/rust:fancy-regex",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:indexmap",
        "bsmr_build//third-party/rust:indoc",
        "bsmr_build//third-party/rust:itertools",
        "bsmr_build//third-party/rust:ref-cast",
        "bsmr_build//third-party/rust:tokio",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_query_derive:bsmr_query_derive",
        "root//app/bsmr_query_parser:bsmr_query_parser",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/gazebo/display_container:display_container",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/pagable/pagable:pagable",
        "root//packages/rust/starlark/starlark_map:starlark_map",
    ],
)
