# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_action_metadata_proto.

load("@bsmr_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")

oncall("build_infra")

rust_protobuf_library(
    name = "bsmr_action_metadata_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bsmr_action_metadata_proto.proto",
)

proto_srcs(
    name = "bsmr_action_metadata_proto.proto",
    srcs = ["action_metadata.proto"],
    visibility = ["PUBLIC"],
)
