load("@char_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")
load("@char_build//rules:export_files.bzl", "export_file")
load("@char_build//rules:targets.bzl", "translate_target")

oncall("build_infra")

rust_protobuf_library(
    name = "buck2_cli_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":buck2_cli_proto.proto",
    test_deps = [
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:tokio",
    ],
    deps = [
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio-util",
        "//buck2/packages/rust/allocative/allocative:allocative",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_data:buck2_data",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_fs:buck2_fs",
        "//buck2/app/buck2_subscription_proto:buck2_subscription_proto",
    ],
)

proto_srcs(
    name = "buck2_cli_proto.proto",
    srcs = ["daemon.proto"],
    visibility = ["PUBLIC"],
    deps = [
        translate_target("//buck2/app/buck2_data:data_proto"),
        translate_target("//buck2/app/buck2_subscription_proto:buck2_subscription_proto.proto"),
    ],
)

export_file(
    name = "daemon.proto",
)
