load("@root//tests:buck_e2e.bzl", "bsmr_core_tests")

oncall("build_infra")

bsmr_core_tests(
    target_extra_attrs = {
        "test_help_env": {
            "use_compiled_bsmr_client_and_tpx": True,
        },
    },
)
