load("@fbcode//bsmr/tests:buck_e2e.bzl", "bsmr_core_tests")

oncall("build_infra")

bsmr_core_tests(
    target_extra_attrs = {
        "test_console": {
            "env": {
                "FIXTURES": "$(location //bsmr/tests/core/console/fixtures:fixtures)",
            },
        },
        "test_console_output_limit": {
            "use_compiled_bsmr_client_and_tpx": True,
        },
    },
)
