# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@prelude//utils:source_listing.bzl", "source_listing")
load(":defs.bzl", "generate_tag_constraints")

oncall("build_infra")

source_listing()

generate_tag_constraints()
