load("@fbcode//bsmr/tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("build_infra")

bsmr_e2e_test(
    name = "test_audit_classpath",
    srcs = ["test_audit_classpath.py"],
    skip_for_os = ["windows"],
)
