load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_query_impls",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "bsmr_build//third-party/rust:assert_matches",
    ],
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:dashmap",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:either",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:itertools",
        "bsmr_build//third-party/rust:ref-cast",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tracing",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_artifact:bsmr_artifact",
        "root//app/bsmr_build_api:bsmr_build_api",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_interpreter:bsmr_interpreter",
        "root//app/bsmr_node:bsmr_node",
        "root//app/bsmr_query:bsmr_query",
        "root//app/bsmr_query_parser:bsmr_query_parser",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/dice/dice_futures:dice_futures",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/pagable/pagable:pagable",
        "root//packages/rust/starlark/starlark:starlark",
    ],
)
