// @generated by Hollywood. Do not edit by hand.
//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Implements the artifact checksum action.


import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { verifySha256Action } from "../../../../../ci/verify-sha256.ts";

void runGitHubAction(verifySha256Action);
