# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_build_api.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_build_api",
    srcs = glob(["src/**/*.rs"]),
    # `root//packages/rust/remote_execution:remote_execution` is an alias selecting between
    # the internal and OSS impls; autocargo doesn't follow aliases, so point at
    # the OSS rust_library directly for cargo's sake.
    autocargo = {
        "cargo_toml_config": {
            "extra_buck_dependencies": {
                "dependencies": [
                    "root//packages/rust/remote_execution/oss/re_grpc:remote_execution",
                ],
            },
        },
    },
    test_deps = [
        "root//app/bsmr_certs:bsmr_certs",
        "root//app/bsmr_wrapper_common:bsmr_wrapper_common",
    ],
    deps = [
        "bsmr_build//third-party/rust:async-recursion",
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:blake3",
        "bsmr_build//third-party/rust:console",
        "bsmr_build//third-party/rust:derivative",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:either",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:indexmap",
        "bsmr_build//third-party/rust:internment",
        "bsmr_build//third-party/rust:inventory",
        "bsmr_build//third-party/rust:itertools",
        "bsmr_build//third-party/rust:linkme",
        "bsmr_build//third-party/rust:multimap",
        "bsmr_build//third-party/rust:ref-cast",
        "bsmr_build//third-party/rust:regex",
        "bsmr_build//third-party/rust:serde",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:smallvec",
        "bsmr_build//third-party/rust:sorted_vector_map",
        "bsmr_build//third-party/rust:static_assertions",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tracing",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_artifact:bsmr_artifact",
        "root//app/bsmr_build_api_derive:bsmr_build_api_derive",
        "root//app/bsmr_build_info:bsmr_build_info",
        "root//app/bsmr_build_signals:bsmr_build_signals",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_directory:bsmr_directory",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_errorformat:bsmr_errorformat",
        "root//app/bsmr_event_observer:bsmr_event_observer",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_execute:bsmr_execute",
        "root//app/bsmr_file_watcher:bsmr_file_watcher",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_http:bsmr_http",
        "root//app/bsmr_interpreter:bsmr_interpreter",
        "root//app/bsmr_node:bsmr_node",
        "root//app/bsmr_query:bsmr_query",
        "root//app/bsmr_test_api:bsmr_test_api",
        "root//app/bsmr_util:bsmr_util",
        "root//app/bsmr_wrapper_common:bsmr_wrapper_common",
        "root//app/bsmr_sketches:bsmr_sketches",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/dice/dice_futures:dice_futures",
        "root//packages/rust/gazebo/display_container:display_container",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/gazebo/strong_hash:strong_hash",
        "root//packages/rust/pagable/pagable:pagable",
        "root//packages/rust/remote_execution:remote_execution",
        "root//packages/rust/setsketch:setsketch",
        "root//packages/rust/starlark/starlark:starlark",
        "root//packages/rust/starlark/starlark_map:starlark_map",
    ],
)
