// @generated by Hollywood. Do not edit by hand.
//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Implements the CLI-reference action.


import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { cliReferenceAction } from "../../../../../ci/cli-reference.ts";

void runGitHubAction(cliReferenceAction);
