load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("bsmr")

rust_library(
    name = "bsmr_error_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    proc_macro = True,
    deps = [
        "bsmr_build//third-party/rust:proc-macro2",
        "bsmr_build//third-party/rust:quote",
        "bsmr_build//third-party/rust:syn",
    ],
)
