// @generated by Hollywood. Do not edit by hand.
//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Implements the native TypeScript cache verification action.


import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { typescriptCache } from "../../../../../ci/typescript/cache.ts";

void runGitHubAction(typescriptCache);
