# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines the stable Bessemer build-event protocol target.

load("@bsmr_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")
load("@bsmr_build//rules:export_files.bzl", "export_file")

oncall("build_infra")

rust_protobuf_library(
    name = "bsmr_build_event_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bsmr_build_event_proto.proto",
    deps = ["bsmr_build//third-party/rust:serde"],
)

proto_srcs(
    name = "bsmr_build_event_proto.proto",
    srcs = ["build_event.proto"],
    visibility = ["PUBLIC"],
)

export_file(
    name = "build_event.proto",
)
