load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_fs",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "extra_buck_dependencies": {
                "dependencies": [
                    (None, "//common/rust/shed/detect_eden:detect_eden"),
                ],
            },
        },
    },
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:tempfile",
        "//bsmr/app/bsmr_hash:bsmr_hash",
    ],
    deps = [
        "fbsource//third-party/rust:compact_str",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:dunce",
        "fbsource//third-party/rust:memchr",
        "fbsource//third-party/rust:ref-cast",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:smallvec",
        "fbsource//third-party/rust:tokio",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_env:bsmr_env",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/gazebo:gazebo",
        "//bsmr/packages/rust/gazebo/strong_hash:strong_hash",
        "//bsmr/packages/rust/pagable/pagable:pagable",
        # @oss-disable[end= ]: "//common/rust/shed/detect_eden:detect_eden",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:libc",
            "fbsource//third-party/rust:nix",
        ],
        "ovr_config//os:macos": [
            "fbsource//third-party/rust:libc",
            "fbsource//third-party/rust:nix",
        ],
        "ovr_config//os:windows": [
            "fbsource//third-party/rust:common-path",
            "fbsource//third-party/rust:windows-sys",
        ],
    }),
)
