load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_eden",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {"ignore_rule": True},
    named_deps = {
        # @oss-disable[end= ]: "edenfs": "//eden/fs/service:thrift-rust",
        # @oss-disable[end= ]: "edenfs_clients": "//eden/fs/service:thrift-rust-clients",
    },
    deps = [
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:async-trait",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:compact_str",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:curl-sys",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:futures",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:libc",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:parking_lot",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:serde",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:tokio",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:toml",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:tracing",
        # @oss-disable[end= ]: "root//packages/rust/allocative/allocative:allocative",
        # @oss-disable[end= ]: "root//app/bsmr_certs:bsmr_certs",
        # @oss-disable[end= ]: "root//app/bsmr_common:bsmr_common",
        # @oss-disable[end= ]: "root//app/bsmr_core:bsmr_core",
        # @oss-disable[end= ]: "root//app/bsmr_error:bsmr_error",
        # @oss-disable[end= ]: "root//app/bsmr_fs:bsmr_fs",
        # @oss-disable[end= ]: "root//packages/rust/gazebo/dupe:dupe",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:fbinit",
        # @oss-disable[end= ]: "bsmr_build//third-party/rust:sorted_vector_map",
        # @oss-disable[end= ]: "//common/rust/thrift/bareclient:thriftclient",
        # @oss-disable[end= ]: "//fb303/thrift:fb303_core-rust-clients",
        # @oss-disable[end= ]: "//thrift/lib/rust:fbthrift",
    ],
)
