load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_critical_path",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:rand",
        "fbsource//third-party/rust:rand_chacha",
        "fbsource//third-party/rust:rand_distr",
    ],
    deps = [
        "fbsource//third-party/rust:crossbeam",
        "fbsource//third-party/rust:derive_more",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/packages/rust/starlark/starlark_map:starlark_map",
    ],
)
