load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("rust_foundation")

rust_library(
    name = "c",
    srcs = ["lib.rs"],
    visibility = ["PUBLIC"],
    deps = ["//buck2/tools/rust-project/tests/targets/foo:e"],
)

rust_library(
    name = "d",
    srcs = ["lib.rs"],
    visibility = ["PUBLIC"],
    deps = ["//buck2/tools/rust-project/tests/targets/foo:e"],
)
