load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_query_parser",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:enum-map",
        "bsmr_build//third-party/rust:nom",
        "bsmr_build//third-party/rust:nom-language",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
    ],
)
