load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_http",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "bsmr_build//third-party/rust:httptest",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "bsmr_build//third-party/rust:tempfile",
        ],
        "ovr_config//os:macos": [
            "bsmr_build//third-party/rust:tempfile",
        ],
    }),
    deps = [
        "bsmr_build//third-party/rust:bytes",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:http",
        "bsmr_build//third-party/rust:http-body-util",
        "bsmr_build//third-party/rust:hyper",
        "bsmr_build//third-party/rust:hyper-http-proxy",
        "bsmr_build//third-party/rust:hyper-rustls",
        "bsmr_build//third-party/rust:hyper-timeout",
        "bsmr_build//third-party/rust:hyper-util",
        "bsmr_build//third-party/rust:ipnetwork",
        "bsmr_build//third-party/rust:pin-project",
        "bsmr_build//third-party/rust:rustls",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tokio-rustls",
        "bsmr_build//third-party/rust:tokio-util",
        "bsmr_build//third-party/rust:tower-service",
        "bsmr_build//third-party/rust:tracing",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_certs:bsmr_certs",
        "root//app/bsmr_error:bsmr_error",
        "root//packages/rust/gazebo/dupe:dupe",
        # @oss-disable[end= ]: "//common/rust/cpe:cpe",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "bsmr_build//third-party/rust:hyperlocal",
        ],
        "ovr_config//os:macos": [
            "bsmr_build//third-party/rust:hyperlocal",
        ],
    }),
)
