load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_test_api",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "bsmr_build//third-party/rust:assert_matches",
    ],
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:derivative",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:prost-types",
        "bsmr_build//third-party/rust:sorted_vector_map",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tonic",
        "bsmr_build//third-party/rust:tower-layer",
        "bsmr_build//third-party/rust:tower-service",
        "bsmr_build//third-party/rust:tracing",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_downward_api:bsmr_downward_api",
        "root//app/bsmr_downward_api_proto:bsmr_downward_api_proto",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_grpc:bsmr_grpc",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_host_sharing_proto:bsmr_host_sharing_proto",
        "root//app/bsmr_test_proto:bsmr_test_proto",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/host_sharing:host_sharing",
        "root//packages/rust/pagable/pagable:pagable",
    ],
)
