# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_client.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_client",
    srcs = glob([
        "src/**/*.rs",
    ]),
    test_deps = [
        "bsmr_build//third-party/rust:assert_matches",
        "bsmr_build//third-party/rust:tempfile",
    ],
    deps = [
        "bsmr_build//third-party/rust:async-recursion",
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:bytesize",
        "bsmr_build//third-party/rust:chrono",
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:humantime",
        "bsmr_build//third-party/rust:libc",
        "bsmr_build//third-party/rust:lsp-server",
        "bsmr_build//third-party/rust:prost",
        "bsmr_build//third-party/rust:serde",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:shlex",
        "bsmr_build//third-party/rust:threadpool",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tokio-stream",
        "bsmr_build//third-party/rust:tokio-util",
        "bsmr_build//third-party/rust:tonic",
        "bsmr_build//third-party/rust:tracing",
        "bsmr_build//third-party/rust:uuid",
        "bsmr_build//third-party/rust:walkdir",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_client_ctx:bsmr_client_ctx",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_event_log:bsmr_event_log",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_query_parser:bsmr_query_parser",
        "root//app/bsmr_subscription_proto:bsmr_subscription_proto",
        "root//app/bsmr_util:bsmr_util",
        "root//app/bsmr_wrapper_common:bsmr_wrapper_common",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/superconsole:superconsole",
    ],
)
