# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load(":graph_utils_tests.bzl", "test_find_cycle")
load(":headers_tests.bzl", "test_infer_include_prefix")
load(":link_info_tests.bzl", "test_get_lib_output_style")

oncall("build_infra")

test_get_lib_output_style()

test_find_cycle()

test_infer_include_prefix()
