// @generated by Hollywood. Do not edit by hand.
//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Implements the release-state action.


import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { releaseStateAction } from "../../../../../ci/release-state.ts";

void runGitHubAction(releaseStateAction);
