# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_cmd_docs_server.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_cmd_docs_server",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:serde",
        "bsmr_build//third-party/rust:serde_json",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_interpreter:bsmr_interpreter",
        "root//app/bsmr_interpreter_for_build:bsmr_interpreter_for_build",
        "root//app/bsmr_server_ctx:bsmr_server_ctx",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/starlark/starlark:starlark",
    ],
)
