load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_cmd_docs_server",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "//bsmr/app/bsmr_cli_proto:bsmr_cli_proto",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_interpreter:bsmr_interpreter",
        "//bsmr/app/bsmr_interpreter_for_build:bsmr_interpreter_for_build",
        "//bsmr/app/bsmr_server_ctx:bsmr_server_ctx",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/starlark/starlark:starlark",
    ],
)
