load("@bsmr_build//rules:native_rules.bzl", "alias")
load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("rust_foundation")

rust_library(
    name = "l",
    srcs = ["lib.rs"],
    unittests = False,
)

alias(
    name = "l_alias",
    actual = ":l",
)
