# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("apple_workflows")

source_listing()

python_binary(
    name = "signing_context_tree_postprocessor",
    main = "main.py",
    visibility = ["PUBLIC"],
)
