# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@root//tests:bxl_test.bzl", "bxl_test")

oncall("build_infra")

bxl_test(
    name = "fs_inplace.bxl",
    src = "fs_inplace.bxl",
)
