# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# FIXME(marwhal): Get python_cextension example working again
# python_binary(
#     name = "cext",
#     deps = ["//cpp/python_cextension:cpprint"],
#     main = "cext/cext.py"
# )

oncall("build_infra")
