load("@bsmr_build//rules:native_rules.bzl", "buck_filegroup")
load("@bsmr_build//rules:rust.bzl", "rust_unittest")

oncall("build_infra")

buck_filegroup(
    name = "tests",
    srcs = glob([
        "src/**/*.golden",
        "src/**",
    ]),
)

rust_unittest(
    name = "bsmr_error_tests",
    srcs = glob(["src/**/*.rs"]),
    env = {
        # Some of our tests include testcase files relative to CARGO_MANIFEST_DIR.
        # This is a hack that allows both `cargo test` and `buck test` to work.
        "CARGO_MANIFEST_DIR": "$(location :tests)",
    },
    deps = [
        "bsmr_build//third-party/rust:anyhow",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/starlark/starlark:starlark",
    ],
)
