load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_event_log",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "bsmr_build//third-party/rust:maplit",
        "bsmr_build//third-party/rust:tempfile",
        "root//app/bsmr_hash:bsmr_hash",
    ],
    deps = [
        "bsmr_build//third-party/rust:async-compression",
        "bsmr_build//third-party/rust:chrono",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:itertools",
        "bsmr_build//third-party/rust:pin-project",
        "bsmr_build//third-party/rust:prost",
        "bsmr_build//third-party/rust:prost-types",
        "bsmr_build//third-party/rust:regex",
        "bsmr_build//third-party/rust:serde",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:shlex",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tokio-stream",
        "bsmr_build//third-party/rust:tokio-util",
        "bsmr_build//third-party/rust:tracing",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_event_observer:bsmr_event_observer",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_util:bsmr_util",
        "root//app/bsmr_wrapper_common:bsmr_wrapper_common",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
    ],
)
