# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_sketches.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_sketches",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "bsmr_build//third-party/rust:base64",
        "root//packages/rust/setsketch:setsketch",
    ],
)
