load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_resource_control",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        # @oss-disable[end= ]: "//common/rust/environment:environment",
    ],
    test_env = {
        "PREP_CGROUP_SCRIPT": "$(location fbcode//bsmr/tools/testing/cgroups:prep_cgroup)",
        "USE_SOME_MEMORY_BIN": "$(location //bsmr/tools/testing/cgroups/use_some_memory:use_some_memory)",
    },
    deps = [
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:ref-cast",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-util",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/app/bsmr_wrapper_common:bsmr_wrapper_common",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:nix",
        ],
        "ovr_config//os:macos": [
            "fbsource//third-party/rust:nix",
        ],
    }),
)
