// @generated by Hollywood. Do not edit by hand.
//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Implements native OCI cache qualification.


import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { ociCache } from "../../../../../ci/oci/cache.ts";

void runGitHubAction(ociCache);
