load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_offline_archive",
    srcs = glob(["src/**/*.rs"]),
    test_deps = select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "bsmr_build//third-party/rust:tempfile",
        ],
        "ovr_config//os:macos": [
            "bsmr_build//third-party/rust:tempfile",
        ],
    }),
    deps = [
        "bsmr_build//third-party/rust:serde",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_util:bsmr_util",
    ],
)
