# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@bsmr_build//rules:rust.bzl", "rust_binary")

oncall("build_infra")

rust_binary(
    name = "use_some_memory",
    srcs = ["use_some_memory.rs"],
    crate_root = "use_some_memory.rs",
    deps = [
        "bsmr_build//third-party/rust:clap",
    ],
)
