load("@bsmr_build//rules:rust.bzl", "rust_binary")

oncall("build_infra")

rust_binary(
    name = "use_some_memory",
    srcs = ["use_some_memory.rs"],
    crate_root = "use_some_memory.rs",
    deps = [
        "fbsource//third-party/rust:clap",
    ],
)
