# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@root//tests/prelude:py_assertion.bzl", "py_assertion")

oncall("golang")

prelude = native

prelude.go_test(
    name = "test",
    srcs = [
        "coverage.go",
        "coverage_test.go",
    ],
    coverage_mode = "set",
    # @oss-disable[end= ]: env = {"GO_TEST2JSON_TOOL": "$(exe_target upstream//third-party/go:test2json)"},
)

py_assertion(
    name = "check_coverage",
    script = """
import subprocess
import sys
result = subprocess.check_output([sys.argv[1]], stderr=subprocess.STDOUT, text=True)
assert "coverage: 100.0% of statements in bsmr/tests/prelude/go/go_test/coverage" in result
""",
    script_args = ["$(location_exec :test)"],
)
