load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_file_watcher",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {
        "cargo_toml_config": {
            "dependencies_override": {
                "dependencies": {
                    "fbinit": {
                        "path": None,
                        "version": "0.2",
                    },
                    "watchman_client": {
                        "path": None,
                        "version": "0.9.0",
                    },
                },
            },
            "extra_buck_dependencies": {
                "dependencies": [
                    (None, "//common/rust/shed/detect_eden:detect_eden"),
                    (None, "//eden/fs/service:thrift-rust"),
                ],
            },
        },
    },
    named_deps = {
        # @oss-disable[end= ]: "edenfs": "//eden/fs/service:thrift-rust",
    },
    test_deps = [
        "fbsource//third-party/rust:tempfile",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:assert_matches",
            "//bsmr/app/bsmr_util:bsmr_util",
            "//bsmr/packages/rust/gazebo/gazebo:gazebo",
        ],
        "ovr_config//os:macos": [
            "fbsource//third-party/rust:assert_matches",
            "//bsmr/app/bsmr_util:bsmr_util",
            "//bsmr/packages/rust/gazebo/gazebo:gazebo",
        ],
    }),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:blake3",
        "fbsource//third-party/rust:compact_str",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:hex",
        "fbsource//third-party/rust:notify",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:uuid",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_certs:bsmr_certs",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_eden:bsmr_eden",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/starlark/starlark_map:starlark_map",
        # @oss-disable[end= ]: "//common/rust/shed/detect_eden:detect_eden",
        "//common/rust/shed/fbinit:fbinit",
        "//watchman/rust/watchman_client:watchman_client",
    ],
)
