load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_execute_impl",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    # `//bsmr/packages/rust/remote_execution:remote_execution` is an alias selecting between
    # the internal and OSS impls; autocargo doesn't follow aliases, so point at
    # the OSS rust_library directly for cargo's sake.
    autocargo = {
        "cargo_toml_config": {
            "extra_buck_dependencies": {
                "dependencies": [
                    "fbcode//bsmr/packages/rust/remote_execution/oss/re_grpc:remote_execution",
                ],
                "target": {
                    "'cfg(target_os = \"linux\")'": {"dependencies": [(None, "//common/rust/shed/hostcaps:hostcaps")]},
                },
            },
        },
    },
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
    ],
    deps = [
        "fbsource//third-party/rust:async-condvar-fair",
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:chrono",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:hostname",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:parking_lot",
        "fbsource//third-party/rust:pin-project",
        "fbsource//third-party/rust:prost",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:rusqlite",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-retry",
        "fbsource//third-party/rust:tokio-stream",
        "fbsource//third-party/rust:tonic",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:zstd",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_action_metadata_proto:bsmr_action_metadata_proto",
        "//bsmr/app/bsmr_build_signals:bsmr_build_signals",
        "//bsmr/app/bsmr_cli_proto:bsmr_cli_proto",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_directory:bsmr_directory",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_execute:bsmr_execute",
        "//bsmr/app/bsmr_execute_local:bsmr_execute_local",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_http:bsmr_http",
        "//bsmr/app/bsmr_resource_control:bsmr_resource_control",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/app/bsmr_worker_proto:bsmr_worker_proto",
        "//bsmr/app/bsmr_wrapper_common:bsmr_wrapper_common",
        "//bsmr/packages/rust/dice/dice_futures:dice_futures",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/gazebo:gazebo",
        "//bsmr/packages/rust/host_sharing:host_sharing",
        "//bsmr/packages/rust/remote_execution:remote_execution",
        "//bsmr/packages/rust/starlark/starlark_map:starlark_map",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "//bsmr/app/bsmr_forkserver:bsmr_forkserver",
            "//bsmr/app/bsmr_forkserver_proto:bsmr_forkserver_proto",
            # @oss-disable[end= ]: "//common/rust/shed/hostcaps:hostcaps",
            # @oss-disable[end= ]: "//justknobs/rust:justknobs",
        ],
        "ovr_config//os:macos": [
            "//bsmr/app/bsmr_forkserver:bsmr_forkserver",
            "//bsmr/app/bsmr_forkserver_proto:bsmr_forkserver_proto",
        ],
    }),
)
