# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@prelude//toolchains/android/tools:protobuf.bzl", "protobuf_src_gen")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

protobuf_src_gen(
    name = "installer-model",
    srcs = [
        "install.proto",
    ],
    proto_path = [],
    deps = [
        "prelude//toolchains/android/third-party:jakarta.annotation-api",
    ],
    exported_deps = [
        "prelude//toolchains/android/third-party:protobuf",
        "prelude//toolchains/android/third-party:remote-apis",
    ],
)
