load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_cmd_docs_client",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:regex",
        "bsmr_build//third-party/rust:termimad",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_client_ctx:bsmr_client_ctx",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_query:bsmr_query",
        "root//packages/rust/gazebo/dupe:dupe",
    ],
)
