//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Renders and synchronizes Bessemer manifests owned by the Go frontend.

//! Owns the generated-manifest lifecycle for the native Go frontend.
//!
//! Generated manifests are intermediate representation, not a second developer API.
//! The ownership marker and `.bsmr-go-manifests` index form the deletion boundary:
//! synchronization never overwrites or removes a file it cannot prove it generated.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;

use crate::commands::go_graph::GoGraph;
use crate::commands::go_graph::GoPackage;

const GENERATED_MARKER: &str = "# Generated by `bsmr go sync`; DO NOT EDIT.";
const INDEX_FILE: &str = ".bsmr-go-manifests";

/// Selects whether synchronization writes files or only verifies them.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum SyncMode {
    /// Persist the expected graph and remove previously indexed stale manifests.
    Write,
    /// Report drift without mutating manifests or the ownership index.
    Check,
}

/// Counts material changes made by one synchronization.
#[derive(Debug, Eq, PartialEq)]
pub(crate) struct SyncReport {
    /// Counts expected manifests whose content changed on disk.
    written: usize,
    /// Counts obsolete, frontend-owned manifests removed from disk.
    removed: usize,
}

impl SyncReport {
    /// Returns the number of generated files written or replaced.
    pub(crate) fn written(&self) -> usize {
        self.written
    }

    /// Returns the number of obsolete generated files removed.
    pub(crate) fn removed(&self) -> usize {
        self.removed
    }
}

/// Errors that protect generated manifests from drift or accidental overwrite.
#[derive(Debug, bsmr_error::Error)]
#[bsmr(tag = Input)]
pub(crate) enum GoManifestError {
    #[error("failed to serialize generated Go manifest: {0}")]
    Serialize(String),
    #[error("failed to read `{path:?}`: {message}")]
    Read { path: PathBuf, message: String },
    #[error("failed to write `{path:?}`: {message}")]
    Write { path: PathBuf, message: String },
    #[error("refusing to overwrite user-owned Go manifest `{0:?}`")]
    UserOwned(PathBuf),
    #[error("generated Go manifests are stale: {0}")]
    Stale(String),
    #[error("generated Go manifest index contains unsafe path `{0}`")]
    UnsafeIndexPath(String),
}

/// Renders one repository-local package as ordinary Bessemer Go rules.
pub(crate) fn render_manifest(
    package: &GoPackage,
    build_tags: &[String],
    cgo_enabled: bool,
) -> Result<String, GoManifestError> {
    let mut output = String::from(
        "# ===----------------------------------------------------------------------===\n\
         # Copyright (c) 2026 Dedalus Labs, Inc. and its contributors\n\
         # SPDX-License-Identifier: Apache-2.0\n\
         # ===----------------------------------------------------------------------===\n\n",
    );
    output.push_str(GENERATED_MARKER);
    output.push_str("\n\n");
    render_build_target(&mut output, package, build_tags, cgo_enabled)?;
    if !package.test_files().is_empty() {
        output.push('\n');
        render_test_target(&mut output, package, build_tags, cgo_enabled)?;
    }
    if !package.external_test_files().is_empty() {
        output.push('\n');
        render_external_test_target(&mut output, package, build_tags, cgo_enabled)?;
    }
    Ok(output)
}

/// Synchronizes all generated manifests and their deterministic ownership index.
pub(crate) fn sync_manifests(
    root: &Path,
    graph: &GoGraph,
    buildfile: &str,
    build_tags: &[String],
    cgo_enabled: bool,
    mode: SyncMode,
) -> Result<SyncReport, GoManifestError> {
    let expected = expected_manifests(root, graph, buildfile, build_tags, cgo_enabled)?;
    let index_path = root.join(INDEX_FILE);
    let previous = read_index(&index_path)?;
    validate_existing(&expected)?;
    let stale = previous
        .difference(&expected.keys().cloned().collect())
        .cloned()
        .collect::<BTreeSet<_>>();
    validate_stale(&stale)?;
    if mode == SyncMode::Check {
        return check_manifests(&expected, &previous, &stale);
    }
    let written = write_changed(&expected)?;
    let removed = remove_stale(&stale)?;
    write_index(&index_path, expected.keys())?;
    Ok(SyncReport { written, removed })
}

/// Renders every package and keys it by repository-relative manifest path.
fn expected_manifests(
    root: &Path,
    graph: &GoGraph,
    buildfile: &str,
    build_tags: &[String],
    cgo_enabled: bool,
) -> Result<BTreeMap<PathBuf, String>, GoManifestError> {
    let mut expected = BTreeMap::new();
    for package in graph.packages() {
        let path = root.join(package.relative_dir()).join(buildfile);
        expected.insert(path, render_manifest(package, build_tags, cgo_enabled)?);
    }
    Ok(expected)
}

/// Ensures every existing destination is either current or frontend-owned.
fn validate_existing(expected: &BTreeMap<PathBuf, String>) -> Result<(), GoManifestError> {
    for (path, content) in expected {
        let Some(existing) = read_optional(path)? else {
            continue;
        };
        if existing != *content && !is_generated(&existing) {
            return Err(GoManifestError::UserOwned(path.clone()));
        }
    }
    Ok(())
}

/// Ensures obsolete index entries cannot delete user-owned files.
fn validate_stale(stale: &BTreeSet<PathBuf>) -> Result<(), GoManifestError> {
    for path in stale {
        let Some(existing) = read_optional(path)? else {
            continue;
        };
        if !is_generated(&existing) {
            return Err(GoManifestError::UserOwned(path.clone()));
        }
    }
    Ok(())
}

/// Validates generated content and the index without mutating the repository.
fn check_manifests(
    expected: &BTreeMap<PathBuf, String>,
    previous: &BTreeSet<PathBuf>,
    stale: &BTreeSet<PathBuf>,
) -> Result<SyncReport, GoManifestError> {
    let mut drift = Vec::new();
    for (path, content) in expected {
        if read_optional(path)?.as_deref() != Some(content) {
            drift.push(path.display().to_string());
        }
    }
    if !stale.is_empty() || previous.len() != expected.len() {
        drift.push(INDEX_FILE.to_owned());
    }
    if !drift.is_empty() {
        return Err(GoManifestError::Stale(drift.join(", ")));
    }
    Ok(SyncReport {
        written: 0,
        removed: 0,
    })
}

/// Writes only changed manifests using same-directory atomic persistence.
fn write_changed(expected: &BTreeMap<PathBuf, String>) -> Result<usize, GoManifestError> {
    let mut written = 0;
    for (path, content) in expected {
        if read_optional(path)?.as_deref() == Some(content) {
            continue;
        }
        let parent = path.parent().ok_or_else(|| GoManifestError::Write {
            path: path.clone(),
            message: "manifest path has no parent".to_owned(),
        })?;
        fs::create_dir_all(parent).map_err(|error| write_error(path, error))?;
        atomic_write(path, content.as_bytes())?;
        written += 1;
    }
    Ok(written)
}

/// Removes obsolete generated manifests recorded by the prior index.
fn remove_stale(stale: &BTreeSet<PathBuf>) -> Result<usize, GoManifestError> {
    let mut removed = 0;
    for path in stale {
        if path.exists() {
            fs::remove_file(path).map_err(|error| write_error(path, error))?;
            removed += 1;
        }
    }
    Ok(removed)
}

/// Recognizes only the exact generated preamble owned by this frontend.
fn is_generated(content: &str) -> bool {
    content.lines().nth(5) == Some(GENERATED_MARKER)
        || content == crate::commands::init::INITIAL_ROOT_MANIFEST
}

/// Reads the prior relative-path ownership index.
fn read_index(path: &Path) -> Result<BTreeSet<PathBuf>, GoManifestError> {
    let Some(content) = read_optional(path)? else {
        return Ok(BTreeSet::new());
    };
    if content.lines().next() != Some(GENERATED_MARKER) {
        return Err(GoManifestError::UserOwned(path.to_owned()));
    }
    let root = path.parent().ok_or_else(|| GoManifestError::Read {
        path: path.to_owned(),
        message: "index path has no parent".to_owned(),
    })?;
    content
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            let path = PathBuf::from(line);
            if path.is_absolute()
                || path
                    .components()
                    .any(|part| matches!(part, std::path::Component::ParentDir))
            {
                Err(GoManifestError::UnsafeIndexPath(line.to_owned()))
            } else {
                Ok(root.join(path))
            }
        })
        .collect()
}

/// Writes the relative-path ownership index in sorted order.
fn write_index<'a>(
    path: &Path,
    absolute_paths: impl Iterator<Item = &'a PathBuf>,
) -> Result<(), GoManifestError> {
    let root = path.parent().ok_or_else(|| GoManifestError::Write {
        path: path.to_owned(),
        message: "index path has no parent".to_owned(),
    })?;
    let mut content = format!("{GENERATED_MARKER}\n");
    for absolute in absolute_paths {
        let relative = absolute
            .strip_prefix(root)
            .map_err(|error| GoManifestError::Write {
                path: absolute.clone(),
                message: error.to_string(),
            })?;
        content.push_str(&relative.to_string_lossy());
        content.push('\n');
    }
    atomic_write(path, content.as_bytes())
}

/// Reads UTF-8 text if a path exists.
fn read_optional(path: &Path) -> Result<Option<String>, GoManifestError> {
    match fs::read_to_string(path) {
        Ok(content) => Ok(Some(content)),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(error) => Err(GoManifestError::Read {
            path: path.to_owned(),
            message: error.to_string(),
        }),
    }
}

/// Persists bytes atomically in the destination directory.
fn atomic_write(path: &Path, bytes: &[u8]) -> Result<(), GoManifestError> {
    let parent = path.parent().ok_or_else(|| GoManifestError::Write {
        path: path.to_owned(),
        message: "path has no parent".to_owned(),
    })?;
    let mut temporary =
        tempfile::NamedTempFile::new_in(parent).map_err(|error| write_error(path, error))?;
    temporary
        .write_all(bytes)
        .map_err(|error| write_error(path, error))?;
    temporary
        .persist(path)
        .map_err(|error| write_error(path, error.error))?;
    Ok(())
}

/// Renders the package's compilation target.
fn render_build_target(
    output: &mut String,
    package: &GoPackage,
    build_tags: &[String],
    cgo_enabled: bool,
) -> Result<(), GoManifestError> {
    let rule = if package.target_name() == "bin" {
        "go_binary"
    } else {
        "go_library"
    };
    output.push_str(rule);
    output.push_str("(\n");
    render_scalar(output, "name", package.target_name())?;
    render_scalar(output, "package_name", package.import_path())?;
    render_list(output, "srcs", package.sources())?;
    render_list(output, "embed_srcs", package.embed_files())?;
    if cgo_enabled {
        render_scalar(output, "header_namespace", "")?;
    }
    if package.target_name() == "bin" {
        render_list(output, "build_tags", build_tags)?;
    }
    render_list(output, "deps", package.dependencies())?;
    render_bool(
        output,
        if package.target_name() == "bin" {
            "cgo_enabled"
        } else {
            "override_cgo_enabled"
        },
        cgo_enabled,
    );
    render_list(output, "visibility", &["PUBLIC".to_owned()])?;
    output.push_str(")\n");
    Ok(())
}

/// Renders the package's internal test target.
fn render_test_target(
    output: &mut String,
    package: &GoPackage,
    build_tags: &[String],
    cgo_enabled: bool,
) -> Result<(), GoManifestError> {
    output.push_str("go_test(\n");
    render_scalar(output, "name", "test")?;
    render_scalar(
        output,
        "target_under_test",
        &format!(":{}", package.target_name()),
    )?;
    render_list(output, "srcs", package.test_files())?;
    render_list(output, "embed_srcs", package.test_embed_files())?;
    if cgo_enabled {
        render_scalar(output, "header_namespace", "")?;
    }
    render_list(output, "build_tags", build_tags)?;
    render_list(output, "deps", package.test_dependencies())?;
    render_bool(output, "cgo_enabled", cgo_enabled);
    output.push_str(")\n");
    Ok(())
}

/// Renders the separate package compiled from `package foo_test` sources.
fn render_external_test_target(
    output: &mut String,
    package: &GoPackage,
    build_tags: &[String],
    cgo_enabled: bool,
) -> Result<(), GoManifestError> {
    output.push_str("go_test(\n");
    render_scalar(output, "name", "external_test")?;
    render_scalar(
        output,
        "package_name",
        &format!("{}_test", package.import_path()),
    )?;
    render_list(output, "srcs", package.external_test_files())?;
    render_list(output, "embed_srcs", package.external_test_embed_files())?;
    if cgo_enabled {
        render_scalar(output, "header_namespace", "")?;
    }
    render_list(output, "build_tags", build_tags)?;
    render_list(output, "deps", package.external_test_dependencies())?;
    render_bool(output, "cgo_enabled", cgo_enabled);
    output.push_str(")\n");
    Ok(())
}

/// Renders one Boolean attribute without string coercion.
fn render_bool(output: &mut String, name: &str, value: bool) {
    output.push_str(&format!(
        "    {name} = {},\n",
        if value { "True" } else { "False" }
    ));
}

/// Renders one quoted scalar attribute.
fn render_scalar(output: &mut String, name: &str, value: &str) -> Result<(), GoManifestError> {
    let value = serde_json::to_string(value)
        .map_err(|error| GoManifestError::Serialize(error.to_string()))?;
    output.push_str(&format!("    {name} = {value},\n"));
    Ok(())
}

/// Renders a quoted list attribute when it is non-empty.
fn render_list(output: &mut String, name: &str, values: &[String]) -> Result<(), GoManifestError> {
    if values.is_empty() {
        return Ok(());
    }
    output.push_str(&format!("    {name} = [\n"));
    for value in values {
        let value = serde_json::to_string(value)
            .map_err(|error| GoManifestError::Serialize(error.to_string()))?;
        output.push_str(&format!("        {value},\n"));
    }
    output.push_str("    ],\n");
    Ok(())
}

/// Converts an I/O failure into a path-rich synchronization error.
fn write_error(path: &Path, error: std::io::Error) -> GoManifestError {
    GoManifestError::Write {
        path: path.to_owned(),
        message: error.to_string(),
    }
}
