# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

prelude = native

prelude.python_bootstrap_binary(
    name = "parse_julia_cmd",
    main = "parse_julia_cmd.py",
    visibility = ["PUBLIC"],
)

# Type checking target for Python tool scripts
prelude.python_library(
    name = "scripts-typing",
    srcs = [
        "parse_julia_cmd.py",
    ],
    typing = True,
)
