# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# cxx_python_extension(
#     name = "cpprint",
#     srcs = ["print.cpp"],
#     base_module = "",
#     deps = [":python-3.10"],
#     visibility = ["PUBLIC"],
# )

# buildifier: disable=no-effect

oncall("build_infra")

cxx_library(
    name = "python-3.10",
    exported_linker_flags = [
        "-L{}".format("/usr/lib64"),
        "-lpython{}".format("3.10"),
    ],
    exported_preprocessor_flags = [
        "-isystem{}".format("/usr/include/python3.10"),
    ],
    visibility = ["PUBLIC"],
) if not host_info().os.is_windows else None
