load("@fbcode//bsmr/tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("build_infra")

bsmr_e2e_test(
    name = "test_bxl",
    srcs = ["test_bxl.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    skip_for_os = [
        "darwin",
    ],
    deps = [
        "//bsmr/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)

bsmr_e2e_test(
    name = "test_bxl_query",
    srcs = ["test_bxl_query.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    deps = [
        "//bsmr/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)

bsmr_e2e_test(
    name = "test_bxl_fs",
    srcs = ["test_bxl_fs.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    deps = [
        "//bsmr/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)

bsmr_e2e_test(
    name = "test_bxl_node_operations",
    srcs = ["test_bxl_node_operations.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    deps = [
        "//bsmr/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)

bsmr_e2e_test(
    name = "test_bxl_lazy_analysis",
    srcs = ["test_bxl_lazy_analysis.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    deps = [
        "//bsmr/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)

bsmr_e2e_test(
    name = "test_bxl_lazy_configured_target_node",
    srcs = ["test_bxl_lazy_configured_target_node.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    deps = [
        "//bsmr/tests/e2e_util:utilities",
    ],
)

bsmr_e2e_test(
    name = "test_bxl_lazy_unconfigured_target_node",
    srcs = ["test_bxl_lazy_unconfigured_target_node.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    deps = [
        "//bsmr/tests/e2e_util:utilities",
    ],
)

bsmr_e2e_test(
    name = "test_bxl_targets",
    srcs = ["test_bxl_targets.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    deps = [
        "//bsmr/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)

bsmr_e2e_test(
    name = "test_bxl_lazy_cquery",
    srcs = ["test_bxl_lazy_cquery.py"],
    data = "//bsmr/tests/targets:isolated_targets",
    env = {
        "OVR_CONFIG": "1",
        "PRELUDE": "$(location prelude//:prelude)",
    },
    deps = [
        "//bsmr/tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)
