load("@char_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_env",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
    ],
    deps = [
        "fbsource//third-party/rust:arc-swap",
        "fbsource//third-party/rust:linkme",
        "fbsource//third-party/rust:tracing",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/packages/rust/gazebo/dupe:dupe",
        "//buck2/packages/rust/starlark/starlark_map:starlark_map",
    ],
)
