load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_execute_local",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
        "fbsource//third-party/rust:sysinfo",
        "fbsource//third-party/rust:tempfile",
        "fbsource//third-party/rust:tokio-stream",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
    ],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:bincode",
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:libc",
        "fbsource//third-party/rust:pin-project",
        "fbsource//third-party/rust:take_mut",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-util",
        "fbsource//third-party/rust:tracing",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_miniperf_proto:bsmr_miniperf_proto",
        "//bsmr/app/bsmr_resource_control:bsmr_resource_control",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:nix",
        ],
        "ovr_config//os:macos": [
            "fbsource//third-party/rust:nix",
        ],
        "ovr_config//os:windows": [
            "fbsource//third-party/rust:windows-sys",
            "//bsmr/app/bsmr_wrapper_common:bsmr_wrapper_common",
            "//bsmr/packages/rust/gazebo/dupe:dupe",
        ],
    }),
)
