load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_cfg_constructor",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "//buck2/packages/rust/allocative/allocative:allocative",
        "//buck2/app/buck2_build_api:buck2_build_api",
        "//buck2/app/buck2_common:buck2_common",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_events:buck2_events",
        "//buck2/app/buck2_interpreter:buck2_interpreter",
        "//buck2/app/buck2_interpreter_for_build:buck2_interpreter_for_build",
        "//buck2/app/buck2_node:buck2_node",
        "//buck2/packages/rust/dice/dice:dice",
        "//buck2/packages/rust/dice/dice_futures:dice_futures",
        "//buck2/packages/rust/gazebo/dupe:dupe",
        "//buck2/packages/rust/pagable/pagable:pagable",
        "//buck2/packages/rust/starlark/starlark:starlark",
    ],
)
