//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Verifies the license policy against an isolated source inventory.

import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import type { ScriptExec } from "@dedalus-labs/hollywood";

import { licenseGeneratedEntrypoints, runLicensePolicy } from "./license.ts";

test("generated action entrypoints retain canonical preambles", () => {
	const root = mkdtempSync(join(tmpdir(), "bsmr-generated-license-"));
	try {
		const paths = [
			".github/actions/ci/osv-audit/src/index.ts",
			".github/actions/ci/rust-affected/src/index.ts",
			".github/actions/ci/verify-sha256/src/index.ts",
		];
		for (const path of paths) {
			mkdirSync(join(root, path, ".."), { recursive: true });
			writeFileSync(join(root, path), "// @generated by Hollywood. Do not edit by hand.\n\nexport {};\n");
		}
		licenseGeneratedEntrypoints(root);
		for (const path of paths) {
			assert.match(readFileSync(join(root, path), "utf8"), /^\/\/ @generated.*\n\/\/===/);
		}
	} finally {
		rmSync(root, { force: true, recursive: true });
	}
});

test("policy accepts canonical source and package licenses", async () => {
	const root = mkdtempSync(join(tmpdir(), "bsmr-license-"));
	try {
		mkdirSync(join(root, "app"));
		writeFileSync(join(root, "LICENSE"), "Apache\n");
		writeFileSync(join(root, "LICENSE-APACHE"), "Apache\n");
		writeFileSync(join(root, "app/BUILD.bsmr"), "# ===----------------------------------------------------------------------===\n# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors\n# SPDX-License-Identifier: Apache-2.0\n# ===----------------------------------------------------------------------===\n\n# Defines build targets for app.\n");
		writeFileSync(join(root, "package.json"), '{"license":"Apache-2.0"}\n');
		let tracked = "app/BUILD.bsmr\0package.json\0";
		const exec: ScriptExec = async (_file, args) => {
			if (args.includes("ls-files")) return { exitCode: 0, stdout: tracked, stderr: "" };
			if (args.includes("--name-status")) return { exitCode: 0, stdout: "A\0app/BUILD.bsmr\0A\0package.json\0", stderr: "" };
			if (args[0] === "metadata") return { exitCode: 0, stdout: '{"packages":[]}', stderr: "" };
			return { exitCode: 0, stdout: "", stderr: "" };
		};
		await assert.doesNotReject(runLicensePolicy("check", root, exec));
		tracked = "app/BUILD.bsmr\0app/BUCK\0package.json\0";
		await assert.rejects(runLicensePolicy("check", root, exec), /app\/BUCK: rename legacy build manifest/);
	} finally {
		rmSync(root, { force: true, recursive: true });
	}
});
