//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Verifies native comment rendering and parser-directive preservation.

import assert from "node:assert/strict";
import { test } from "node:test";

import { insertPreamble, renderPreamble, validateSource } from "./license-preamble.ts";

test("preambles use the file's native comment syntax", () => {
	assert.match(renderPreamble("app/bsmr/BUILD.bsmr", "dedalus"), /^# ===/);
	const modified = renderPreamble("tool.ml", "upstream-modified");
	assert.match(modified, /^\(\* ===.* \*\)$/m);
	assert.doesNotMatch(modified, /Upstream-Source/);
	assert.match(renderPreamble("index.html", "upstream-modified"), /^<!-- ===/);
});

test("insertion preserves interpreter and generator directives", () => {
	const path = ".github/actions/ci/rust-affected/src/index.ts";
	const generated = "// @generated by Hollywood. Do not edit by hand.\n\nexport {};\n";
	assert.ok(insertPreamble({ path, provenance: "dedalus", text: generated }).startsWith(`${generated.split("\n")[0]}\n//===`));
	const script = "#!/usr/bin/env python3\nprint('hello')\n";
	const updated = insertPreamble({ path: "script.py", provenance: "upstream-modified", text: script });
	assert.ok(updated.startsWith("#!/usr/bin/env python3\n# ==="));
	assert.ok(updated.endsWith("print('hello')\n"));
});

test("insertion preserves Markdown frontmatter", () => {
	const text = "---\ntitle: Bessemer\n---\n\nBody\n";
	const updated = insertPreamble({ path: "docs/page.md", provenance: "upstream-modified", text });
	assert.ok(updated.startsWith("---\ntitle: Bessemer\n---\n<!-- ==="));
});

test("validation requires a leading provenance block", () => {
	const path = "app/bsmr/src/lib.rs";
	const preamble = renderPreamble(path, "upstream-modified");
	assert.match(validateSource({ path, provenance: "upstream-modified", text: `// misplaced\n${preamble}` }) ?? "", /missing canonical/);
	assert.equal(validateSource({ path, provenance: "upstream-modified", text: preamble }), undefined);
	const empty = renderPreamble("app/bsmr/BUILD.bsmr", "dedalus").replace("# Defines build targets for app/bsmr.", "# ");
	assert.match(validateSource({ path: "app/bsmr/BUILD.bsmr", provenance: "dedalus", text: empty }) ?? "", /missing source responsibility/);
});
