# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load(
    "@prelude//toolchains/android/tools:build_rules.bzl",
    "buck_java_library",
)
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("android_devxx")

source_listing()

buck_java_library(
    name = "java",
    srcs = glob(["*.java"]),
    visibility = [
        "prelude//toolchains/android/src/com/facebook/buck/...",
        "prelude//toolchains/android/test/com/facebook/buck/...",
    ],
    deps = [
        "prelude//toolchains/android/src/com/facebook/buck/core/util/log:log",
        "prelude//toolchains/android/src/com/facebook/buck/jvm/java:support",
        "prelude//toolchains/android/src/com/facebook/buck/util/zip:zip",
        "prelude//toolchains/android/third-party:guava",
    ],
    exported_deps = [
        "prelude//toolchains/android/src/com/facebook/buck/step/isolatedsteps:isolatedsteps",
        "prelude//toolchains/android/src/com/facebook/buck/step/isolatedsteps/common:common",
    ],
)
