load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("ios_pika")

source_listing()

cxx_binary(
    name = "native_dist_lto_planner",
    srcs = [
        "dist_lto_planner.cpp",
    ],
    compiler_flags = [
        "-Wno-deprecated-declarations",
        "-O2",
    ],
    linker_flags = [
        "-lc",
    ],
    tests = [
        "upstream//xplat/bsmr/tests/apple/rules/dist_lto:main-alias-iphonesimulator-arm64-pika-fat-lld-platform-distributed-thin-lto",
    ],
    visibility = ["PUBLIC"],
    deps = [
        "upstream//common/files:files",
        "upstream//folly:file_util",
        "upstream//folly:json",
        "upstream//folly:subprocess",
        "upstream//folly/coro:blocking_wait",
        "upstream//folly/coro:collect",
        "upstream//folly/coro:shared_mutex",
        "upstream//folly/coro:task",
        "upstream//folly/executors:global_executor",
        "upstream//folly/executors:io_thread_pool_executor",
        "upstream//folly/init:init",
    ],
)
