load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_hash",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:dashmap",
        "fbsource//third-party/rust:fxhash",
        "fbsource//third-party/rust:indexmap",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
    ],
)
