load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

python_binary(
    name = "resource_broker",
    main = "main.py",
    visibility = ["PUBLIC"],
    deps = [
        ":main",
    ],
)

python_library(
    name = "main",
    srcs = ["main.py"],
    deps = [
        ":lib",
    ],
)

python_library(
    name = "lib",
    srcs = glob(
        [
            "*.py",
        ],
        exclude = [
            "main.py",
        ],
    ),
    deps = [
        "upstream//third-party/pypi/dataclasses-json:dataclasses-json",
        "upstream//third-party/pypi/packaging:packaging",
    ],
)
