load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_configured",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:itertools",
        "bsmr_build//third-party/rust:ref-cast",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_build_api:bsmr_build_api",
        "root//app/bsmr_build_signals:bsmr_build_signals",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_node:bsmr_node",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/dice/dice_futures:dice_futures",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/gazebo:gazebo",
        "root//packages/rust/pagable/pagable:pagable",
        "root//packages/rust/starlark/starlark_map:starlark_map",
    ],
)
