load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_test_runner",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:parking_lot",
        "fbsource//third-party/rust:tokio",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_grpc:bsmr_grpc",
        "//bsmr/app/bsmr_test_api:bsmr_test_api",
        "//bsmr/packages/rust/host_sharing:host_sharing",
    ],
)
