# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_test_runner.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_test_runner",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:parking_lot",
        "bsmr_build//third-party/rust:tokio",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_grpc:bsmr_grpc",
        "root//app/bsmr_test_api:bsmr_test_api",
        "root//packages/rust/host_sharing:host_sharing",
    ],
)
