# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_util.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_util",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "root//tools/testing/three-billion-instructions:three_billion_instructions",
        "bsmr_build//third-party/rust:serde_json",
    ],
    deps = [
        "bsmr_build//third-party/rust:blake3",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:regex",
        "bsmr_build//third-party/rust:serde",
        "bsmr_build//third-party/rust:static_assertions",
        "bsmr_build//third-party/rust:sysinfo",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tracing",
        "bsmr_build//third-party/rust:triomphe",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_env:bsmr_env",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_wrapper_common:bsmr_wrapper_common",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/gazebo/strong_hash:strong_hash",
        "root//packages/rust/pagable/pagable:pagable",
        "root//packages/rust/starlark/starlark_map:starlark_map",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "bsmr_build//third-party/rust:libc",
            "bsmr_build//third-party/rust:perf-event",
        ],
        "ovr_config//os:macos": [
            "bsmr_build//third-party/rust:libc",
        ],
        "ovr_config//os:windows": [
            "bsmr_build//third-party/rust:windows-sys",
        ],
    }),
)
