load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_util",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "fbcode//bsmr/tools/testing/three-billion-instructions:three_billion_instructions",
        "fbsource//third-party/rust:serde_json",
    ],
    deps = [
        "fbsource//third-party/rust:blake3",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:static_assertions",
        "fbsource//third-party/rust:sysinfo",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tracing",
        "fbsource//third-party/rust:triomphe",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_env:bsmr_env",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_wrapper_common:bsmr_wrapper_common",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/strong_hash:strong_hash",
        "//bsmr/packages/rust/pagable/pagable:pagable",
        "//bsmr/packages/rust/starlark/starlark_map:starlark_map",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "fbsource//third-party/rust:libc",
            "fbsource//third-party/rust:perf-event",
        ],
        "ovr_config//os:macos": [
            "fbsource//third-party/rust:libc",
        ],
        "ovr_config//os:windows": [
            "fbsource//third-party/rust:windows-sys",
        ],
    }),
)
