load("@root//tests:buck_e2e.bzl", "bsmr_core_tests")

oncall("build_infra")

bsmr_core_tests(
    target_extra_attrs = {
        "test_completion": {
            "env": {
                "BSMR_COMPLETION_VERIFY": "$(location root//tools/testing/completion/verify:completion_verify)",
            },
            "skip_for_os": ["windows"],
        },
    },
)
