// @generated by Hollywood. Do not edit by hand.
//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Installs verified native Rust tooling.


import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { installRust } from "../../../../../ci/runner/rust.ts";

void runGitHubAction(installRust);
