# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@bsmr_build//rules:native_rules.bzl", "buck_filegroup")
# @oss-disable[end= ]: load("root//tests/e2e_util/api:visibility.fb.bzl", "visibility")

oncall("build_infra")

visibility = ["PUBLIC"] # @oss-enable

buck_filegroup(
    name = "nano_prelude",
    srcs = glob(["*.bzl"]),
    visibility = visibility,
)
