load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_cmd_debug_client",
    srcs = glob([
        "src/**/*.rs",
    ]),
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:humantime",
        "bsmr_build//third-party/rust:prost",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tokio-stream",
        "bsmr_build//third-party/rust:tracing",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_client_ctx:bsmr_client_ctx",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_event_log:bsmr_event_log",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_log_common:bsmr_log_common",
        "root//app/bsmr_offline_archive:bsmr_offline_archive",
        "root//app/bsmr_wrapper_common:bsmr_wrapper_common",
        "root//packages/rust/gazebo/gazebo:gazebo",
    ],
)
