load("@bsmr_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")
load("@bsmr_build//rules:export_files.bzl", "export_file")
load("@bsmr_build//rules:targets.bzl", "translate_target")

oncall("build_infra")

rust_protobuf_library(
    name = "bsmr_cli_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bsmr_cli_proto.proto",
    test_deps = [
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:tokio",
    ],
    deps = [
        "fbsource//third-party/rust:bytes",
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:tokio-util",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_subscription_proto:bsmr_subscription_proto",
    ],
)

proto_srcs(
    name = "bsmr_cli_proto.proto",
    srcs = ["daemon.proto"],
    visibility = ["PUBLIC"],
    deps = [
        translate_target("//bsmr/app/bsmr_data:data_proto"),
        translate_target("//bsmr/app/bsmr_subscription_proto:bsmr_subscription_proto.proto"),
    ],
)

export_file(
    name = "daemon.proto",
)
