load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("bsmr")

rust_library(
    name = "bsmr_cmd_query_server",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    test_deps = [],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:indent_write",
        "fbsource//third-party/rust:regex",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "//bsmr/app/bsmr_build_api:bsmr_build_api",
        "//bsmr/app/bsmr_cli_proto:bsmr_cli_proto",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_interpreter:bsmr_interpreter",
        "//bsmr/app/bsmr_node:bsmr_node",
        "//bsmr/app/bsmr_profile:bsmr_profile",
        "//bsmr/app/bsmr_query:bsmr_query",
        "//bsmr/app/bsmr_server_ctx:bsmr_server_ctx",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/gazebo:gazebo",
        "//bsmr/packages/rust/starlark/starlark_map:starlark_map",
    ],
)
