# @oss-disable[end= ]: load("@bsmr_build//rules:rust.bzl", "rust_binary")

oncall("build_infra")

rust_binary(
    name = "main",
    srcs = ["src/main.rs"],
    deps = [
        "fbcode//bsmr/docs/bsmr_lab/greeter_lib:library",
        "fbcode//bsmr/docs/bsmr_lab/logging_lib:logging_lib",
    ],
)
