load("@char_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_test_api",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "fbsource//third-party/rust:assert_matches",
    ],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derivative",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:sorted_vector_map",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tonic",
        "fbsource//third-party/rust:tower-layer",
        "fbsource//third-party/rust:tower-service",
        "fbsource//third-party/rust:tracing",
        "//buck2/packages/rust/allocative/allocative:allocative",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_data:buck2_data",
        "//buck2/app/buck2_downward_api:buck2_downward_api",
        "//buck2/app/buck2_downward_api_proto:buck2_downward_api_proto",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_events:buck2_events",
        "//buck2/app/buck2_fs:buck2_fs",
        "//buck2/app/buck2_grpc:buck2_grpc",
        "//buck2/app/buck2_hash:buck2_hash",
        "//buck2/app/buck2_host_sharing_proto:buck2_host_sharing_proto",
        "//buck2/app/buck2_test_proto:buck2_test_proto",
        "//buck2/packages/rust/gazebo/dupe:dupe",
        "//buck2/packages/rust/gazebo/gazebo:gazebo",
        "//buck2/packages/rust/host_sharing:host_sharing",
        "//buck2/packages/rust/pagable/pagable:pagable",
    ],
)
