# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_error.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("bsmr")

rust_library(
    name = "bsmr_error",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    autocargo = {
        "cargo_toml_config": {
            "dependencies_override": {
                "dependencies": {
                    "watchman_client": {
                        "path": None,
                        "version": "0.9.0",
                    },
                },
            },
            "extra_buck_dependencies": {
                "dependencies": [
                    (None, "//eden/fs/service:thrift-rust-clients"),
                    (None, "//thrift/lib/rust:fbthrift"),
                ],
            },
        },
    },
    named_deps = {
        # @oss-disable[end= ]: "edenfs_clients": "//eden/fs/service:thrift-rust-clients",
    },
    deps = [
        "bsmr_build//third-party/rust:anyhow",
        "bsmr_build//third-party/rust:clap",
        "bsmr_build//third-party/rust:derive_more",
        "bsmr_build//third-party/rust:fancy-regex",
        "bsmr_build//third-party/rust:hex",
        "bsmr_build//third-party/rust:http",
        "bsmr_build//third-party/rust:hyper",
        "bsmr_build//third-party/rust:hyper-util",
        "bsmr_build//third-party/rust:libc",
        "bsmr_build//third-party/rust:prost",
        "bsmr_build//third-party/rust:prost-types",
        "bsmr_build//third-party/rust:ref-cast",
        "bsmr_build//third-party/rust:regex",
        "bsmr_build//third-party/rust:rusqlite",
        "bsmr_build//third-party/rust:rustls-native-certs",
        "bsmr_build//third-party/rust:rustls-pki-types",
        "bsmr_build//third-party/rust:serde",
        "bsmr_build//third-party/rust:serde_json",
        "bsmr_build//third-party/rust:smallvec",
        "bsmr_build//third-party/rust:thiserror",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:toml",
        "bsmr_build//third-party/rust:tonic",
        "bsmr_build//third-party/rust:uuid",
        "root//packages/rust/allocative/allocative:allocative",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error_derive:bsmr_error_derive",
        "root//packages/rust/dice/dice_error:dice_error",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/starlark/starlark_syntax:starlark_syntax",
        "root//packages/rust/superconsole:superconsole",
        # @oss-disable[end= ]: "//thrift/lib/rust:fbthrift",
        "bsmr_build//third-party/rust:watchman_client",
    ] + select({
        "DEFAULT": [],
        "ovr_config//os:linux": [
            "bsmr_build//third-party/rust:nix",
        ],
        "ovr_config//os:macos": [
            "bsmr_build//third-party/rust:nix",
        ],
    }),
)
