load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_cmd_starlark_server",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "bsmr_build//third-party/rust:async-recursion",
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:serde_json",
        "root//app/bsmr_cli_proto:bsmr_cli_proto",
        "root//app/bsmr_client_ctx:bsmr_client_ctx",
        "root//app/bsmr_cmd_starlark_client:bsmr_cmd_starlark_client",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_events:bsmr_events",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_hash:bsmr_hash",
        "root//app/bsmr_interpreter:bsmr_interpreter",
        "root//app/bsmr_interpreter_for_build:bsmr_interpreter_for_build",
        "root//app/bsmr_server_ctx:bsmr_server_ctx",
        "root//packages/rust/dice/dice:dice",
        "root//packages/rust/gazebo/dupe:dupe",
        "root//packages/rust/starlark/starlark:starlark",
    ],
)
