# ===----------------------------------------------------------------------===
# Upstream-Source: facebook/buck2@1560aca2002865cd73d7cafb22c705cfb640b2bc
# Modifications Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

load("@prelude//apple/tools:defs.bzl", "meta_python_test")
load("@prelude//utils:source_listing.bzl", "source_listing")

oncall("build_infra")

source_listing()

python_library(
    name = "lib",
    srcs = [
        "macho.py",
        "macho_parser.py",
        "scrubber.py",
        "spec.py",
        "utils.py",
    ],
    deps = [
        "prelude//apple/tools/re_compatibility_utils:re_compatibility_utils",
    ],
)

python_binary(
    name = "tool",
    main = "main.py",
    visibility = ["PUBLIC"],
    deps = [
        ":lib",
    ],
)

meta_python_test(
    name = "tests",
    srcs = [
        "scrubber_test.py",
        "spec_test.py",
    ],
    resources = glob([
        "test_resources/*",
    ]),
    deps = [
        "upstream//third-party/pypi/importlib-resources:importlib-resources",
        ":lib",
    ],
)
