load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_build_info",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "//bsmr/app/bsmr_util:bsmr_util",
        # @oss-disable[end= ]: "//common/rust/build_info:build_info",
    ],
)
