load("@bsmr_build//rules:rust.bzl", "proto_srcs", "rust_protobuf_library")
load("@bsmr_build//rules:targets.bzl", "translate_target")

oncall("build_infra")

rust_protobuf_library(
    name = "bsmr_test_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = ":bsmr_test_proto.proto",
    deps = [
        "fbsource//third-party/rust:prost-types",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_host_sharing_proto:bsmr_host_sharing_proto",
    ],
)

proto_srcs(
    name = "bsmr_test_proto.proto",
    srcs = ["test.proto"],
    visibility = ["PUBLIC"],
    deps = [
        translate_target("//bsmr/app/bsmr_data:data_proto"),
    ],
)
