load("@root//tests:buck_e2e.bzl", "bsmr_e2e_test")

bsmr_e2e_test(
    name = "test_rust_project",
    srcs = [
        "test_rust_project.py",
    ],
    test_with_compiled_bsmr = False,
    test_with_deployed_bsmr = True,
    deps = [
        "root//tests/e2e_util:utils",  # @autodeps2-fixme-manual
    ],
)
