# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for tests/e2e/bsmr_config.

load("@root//tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("build_infra")

bsmr_e2e_test(
    name = "test_bsmr_config_logging.py",
    srcs = ["test_bsmr_config_logging.py"],
    data_dir = "test_bsmr_config_log_data",
)
