load("@fbcode//bsmr/tests:buck_e2e.bzl", "bsmr_core_tests")

oncall("build_infra")

bsmr_core_tests(
    target_extra_attrs = {
        "test_agent_host_guard": {
            "compatible_with": [
                "ovr_config//os:linux",
                "ovr_config//os:macos",
            ],
        },
    },
)
