load("@root//tests:buck_e2e.bzl", "bsmr_e2e_test")

oncall("build_infra")

bsmr_e2e_test(
    name = "test_targets",
    srcs = ["test_targets.py"],
)

bsmr_e2e_test(
    name = "test_targets_inplace",
    srcs = ["test_targets_inplace.py"],
)
