load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_build_signals_impl",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:prost-types",
        "fbsource//third-party/rust:ref-cast",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:smallvec",
        "fbsource//third-party/rust:static_assertions",
        "fbsource//third-party/rust:tokio",
        "fbsource//third-party/rust:tokio-stream",
        "fbsource//third-party/rust:tracing",
        "//bsmr/app/bsmr_analysis:bsmr_analysis",
        "//bsmr/app/bsmr_artifact:bsmr_artifact",
        "//bsmr/app/bsmr_build_api:bsmr_build_api",
        "//bsmr/app/bsmr_build_signals:bsmr_build_signals",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_critical_path:bsmr_critical_path",
        "//bsmr/app/bsmr_data:bsmr_data",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_events:bsmr_events",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_interpreter_for_build:bsmr_interpreter_for_build",
        "//bsmr/app/bsmr_node:bsmr_node",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/gazebo/gazebo:gazebo",
    ],
)
