load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_health_check",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    test_deps = [
        "bsmr_build//third-party/rust:tempfile",
        "bsmr_build//third-party/rust:tokio",
    ],
    deps = [
        "bsmr_build//third-party/rust:async-trait",
        "bsmr_build//third-party/rust:futures",
        "bsmr_build//third-party/rust:prost-types",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tonic",
        "bsmr_build//third-party/rust:tracing",
        "root//app/bsmr_common:bsmr_common",
        "root//app/bsmr_core:bsmr_core",
        "root//app/bsmr_data:bsmr_data",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_fs:bsmr_fs",
        "root//app/bsmr_health_check_proto:bsmr_health_check_proto",
        "root//app/bsmr_util:bsmr_util",
        "root//packages/rust/gazebo/dupe:dupe",
    ],
)
