// @generated by Hollywood. Do not edit by hand.
//===----------------------------------------------------------------------===//
// Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
// SPDX-License-Identifier: Apache-2.0
//===----------------------------------------------------------------------===//

// Implements the release completion action.


import { runGitHubAction } from "@dedalus-labs/hollywood/action-runtime";
import { completeReleaseAction } from "../../../../../ci/release-complete.ts";

void runGitHubAction(completeReleaseAction);
