load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_external_cells",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "fbsource//third-party/rust:tokio",
    ],
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:blake3",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:tokio",
        "//bsmr/packages/rust/allocative/allocative:allocative",
        "//bsmr/app/bsmr_build_api:bsmr_build_api",
        "//bsmr/app/bsmr_common:bsmr_common",
        "//bsmr/app/bsmr_core:bsmr_core",
        "//bsmr/app/bsmr_directory:bsmr_directory",
        "//bsmr/app/bsmr_error:bsmr_error",
        "//bsmr/app/bsmr_execute:bsmr_execute",
        "//bsmr/app/bsmr_external_cells_bundled:bsmr_external_cells_bundled",
        "//bsmr/app/bsmr_fs:bsmr_fs",
        "//bsmr/app/bsmr_hash:bsmr_hash",
        "//bsmr/app/bsmr_util:bsmr_util",
        "//bsmr/packages/rust/dice/dice:dice",
        "//bsmr/packages/rust/gazebo/cmp_any:cmp_any",
        "//bsmr/packages/rust/gazebo/dupe:dupe",
        "//bsmr/packages/rust/pagable/pagable:pagable",
    ],
)
