# ===----------------------------------------------------------------------===
# Copyright (c) 2026 Dedalus Labs, Inc. and its contributors
# SPDX-License-Identifier: Apache-2.0
# ===----------------------------------------------------------------------===

# Defines build targets for app/bsmr_certs.

load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_certs",
    srcs = glob(["src/**/*.rs"]),
    test_env = {"TEST_CERT_LOCATIONS": "$(source test/testdata)"},
    deps = [
        "bsmr_build//third-party/rust:rustls",
        "bsmr_build//third-party/rust:rustls-native-certs",
        "bsmr_build//third-party/rust:rustls-pki-types",
        "bsmr_build//third-party/rust:tokio",
        "bsmr_build//third-party/rust:tracing",
        "bsmr_build//third-party/rust:x509-parser",
        "root//app/bsmr_error:bsmr_error",
        "root//app/bsmr_util:bsmr_util",
        # @oss-disable[end= ]: "root//facebook/find_certs:find_certs",
        "root//packages/rust/gazebo/dupe:dupe",
        # @oss-disable[end= ]: "//common/rust/cpe:cpe",
    ],
)
