load("@char_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "buck2_query",
    srcs = glob(["src/**/*.rs"]),
    deps = [
        "fbsource//third-party/rust:async-trait",
        "fbsource//third-party/rust:derive_more",
        "fbsource//third-party/rust:enum-iterator",
        "fbsource//third-party/rust:fancy-regex",
        "fbsource//third-party/rust:futures",
        "fbsource//third-party/rust:indexmap",
        "fbsource//third-party/rust:indoc",
        "fbsource//third-party/rust:itertools",
        "fbsource//third-party/rust:ref-cast",
        "fbsource//third-party/rust:tokio",
        "//buck2/packages/rust/allocative/allocative:allocative",
        "//buck2/app/buck2_core:buck2_core",
        "//buck2/app/buck2_error:buck2_error",
        "//buck2/app/buck2_hash:buck2_hash",
        "//buck2/app/buck2_query_derive:buck2_query_derive",
        "//buck2/app/buck2_query_parser:buck2_query_parser",
        "//buck2/app/buck2_util:buck2_util",
        "//buck2/packages/rust/gazebo/display_container:display_container",
        "//buck2/packages/rust/gazebo/dupe:dupe",
        "//buck2/packages/rust/gazebo/gazebo:gazebo",
        "//buck2/packages/rust/pagable/pagable:pagable",
        "//buck2/packages/rust/starlark/starlark_map:starlark_map",
    ],
)
