load("@bsmr_build//rules:rust.bzl", "rust_library")

oncall("build_infra")

rust_library(
    name = "bsmr_miniperf_proto",
    srcs = glob(["src/**/*.rs"]),
    test_deps = [
        "bsmr_build//third-party/rust:bincode",
    ],
    deps = [
        "bsmr_build//third-party/rust:serde",
        "root//app/bsmr_data:bsmr_data",
        "root//packages/rust/gazebo/dupe:dupe",
    ],
)
